/* tslint:disable */
/* eslint-disable */
/**
 * AuthService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeEmailRequest
 */
export interface ChangeEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof ChangeEmailRequest
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmailRequest
     */
    newEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmailRequest
     */
    currentPassword?: string | null;
}

/**
 * Check if a given object implements the ChangeEmailRequest interface.
 */
export function instanceOfChangeEmailRequest(value: object): value is ChangeEmailRequest {
    return true;
}

export function ChangeEmailRequestFromJSON(json: any): ChangeEmailRequest {
    return ChangeEmailRequestFromJSONTyped(json, false);
}

export function ChangeEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'newEmail': json['newEmail'] == null ? undefined : json['newEmail'],
        'currentPassword': json['currentPassword'] == null ? undefined : json['currentPassword'],
    };
}

export function ChangeEmailRequestToJSON(json: any): ChangeEmailRequest {
    return ChangeEmailRequestToJSONTyped(json, false);
}

export function ChangeEmailRequestToJSONTyped(value?: ChangeEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'newEmail': value['newEmail'],
        'currentPassword': value['currentPassword'],
    };
}

