/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisableAccountRequest
 */
export interface DisableAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof DisableAccountRequest
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DisableAccountRequest
     */
    currentPassword?: string | null;
}

/**
 * Check if a given object implements the DisableAccountRequest interface.
 */
export function instanceOfDisableAccountRequest(value: object): value is DisableAccountRequest {
    return true;
}

export function DisableAccountRequestFromJSON(json: any): DisableAccountRequest {
    return DisableAccountRequestFromJSONTyped(json, false);
}

export function DisableAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisableAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'currentPassword': json['currentPassword'] == null ? undefined : json['currentPassword'],
    };
}

export function DisableAccountRequestToJSON(json: any): DisableAccountRequest {
    return DisableAccountRequestToJSONTyped(json, false);
}

export function DisableAccountRequestToJSONTyped(value?: DisableAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'currentPassword': value['currentPassword'],
    };
}

