/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInformationDTO } from './UserInformationDTO';
import {
    UserInformationDTOFromJSON,
    UserInformationDTOFromJSONTyped,
    UserInformationDTOToJSON,
    UserInformationDTOToJSONTyped,
} from './UserInformationDTO';

/**
 * 
 * @export
 * @interface UserInformationResult
 */
export interface UserInformationResult {
    /**
     * 
     * @type {boolean}
     * @memberof UserInformationResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserInformationResult
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {UserInformationDTO}
     * @memberof UserInformationResult
     */
    userInformation?: UserInformationDTO;
}

/**
 * Check if a given object implements the UserInformationResult interface.
 */
export function instanceOfUserInformationResult(value: object): value is UserInformationResult {
    return true;
}

export function UserInformationResultFromJSON(json: any): UserInformationResult {
    return UserInformationResultFromJSONTyped(json, false);
}

export function UserInformationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'userInformation': json['userInformation'] == null ? undefined : UserInformationDTOFromJSON(json['userInformation']),
    };
}

export function UserInformationResultToJSON(json: any): UserInformationResult {
    return UserInformationResultToJSONTyped(json, false);
}

export function UserInformationResultToJSONTyped(value?: UserInformationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'userInformation': UserInformationDTOToJSON(value['userInformation']),
    };
}

