/* tslint:disable */
/* eslint-disable */
/**
 * AuthService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformationDTO
 */
export interface UserInformationDTO {
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    phone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserInformationDTO
     */
    isLinkedInUser?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserInformationDTO
     */
    hasVerifiedLinkedIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserInformationDTO
     */
    isEmailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    linkedInId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    linkedInProfileUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    linkedInHeadline?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserInformationDTO
     */
    lastLinkedInSync?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserInformationDTO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the UserInformationDTO interface.
 */
export function instanceOfUserInformationDTO(value: object): value is UserInformationDTO {
    return true;
}

export function UserInformationDTOFromJSON(json: any): UserInformationDTO {
    return UserInformationDTOFromJSONTyped(json, false);
}

export function UserInformationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'isLinkedInUser': json['isLinkedInUser'] == null ? undefined : json['isLinkedInUser'],
        'hasVerifiedLinkedIn': json['hasVerifiedLinkedIn'] == null ? undefined : json['hasVerifiedLinkedIn'],
        'isEmailConfirmed': json['isEmailConfirmed'] == null ? undefined : json['isEmailConfirmed'],
        'linkedInId': json['linkedInId'] == null ? undefined : json['linkedInId'],
        'linkedInProfileUrl': json['linkedInProfileUrl'] == null ? undefined : json['linkedInProfileUrl'],
        'linkedInHeadline': json['linkedInHeadline'] == null ? undefined : json['linkedInHeadline'],
        'lastLinkedInSync': json['lastLinkedInSync'] == null ? undefined : (new Date(json['lastLinkedInSync'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function UserInformationDTOToJSON(json: any): UserInformationDTO {
    return UserInformationDTOToJSONTyped(json, false);
}

export function UserInformationDTOToJSONTyped(value?: UserInformationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'userName': value['userName'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'isLinkedInUser': value['isLinkedInUser'],
        'hasVerifiedLinkedIn': value['hasVerifiedLinkedIn'],
        'isEmailConfirmed': value['isEmailConfirmed'],
        'linkedInId': value['linkedInId'],
        'linkedInProfileUrl': value['linkedInProfileUrl'],
        'linkedInHeadline': value['linkedInHeadline'],
        'lastLinkedInSync': value['lastLinkedInSync'] == null ? undefined : ((value['lastLinkedInSync'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

