import React from "react";
import {
	AcademicCapIcon,
	BanknotesIcon,
	BeakerIcon,
	BoltIcon,
	BookmarkIcon,
	BriefcaseIcon,
	BuildingOfficeIcon,
	ChartBarIcon,
	ChatBubbleLeftRightIcon,
	CpuChipIcon,
	DocumentTextIcon,
	HeartIcon,
	MegaphoneIcon,
	PresentationChartLineIcon,
	ScaleIcon,
	ShieldCheckIcon,
	ShoppingBagIcon,
	TruckIcon,
	UserCircleIcon,
	WrenchIcon,
	BookOpenIcon
} from "@heroicons/react/24/outline";

const icon = (Icon: React.ElementType, color = "text-primary") => (
	<Icon className={`w-5 h-5 ${color}`} aria-hidden="true" />
);

const defaultIcon = icon(ChartBarIcon, "text-primary");

const categoryIcons: Record<string, React.ReactNode> = {
	"akademisk og politisk arbejde": icon(AcademicCapIcon, "text-secondary"),
	"bibliotek": icon(BookOpenIcon, "text-primary"),
	"blik og rør": icon(WrenchIcon, "text-primary"),
	"bud og udbringning": icon(TruckIcon, "text-info"),
	"bygge og anlæg": icon(WrenchIcon, "text-primary"),
	"bygge- og anlægsteknik": icon(WrenchIcon, "text-primary"),
	"børnepasning": icon(HeartIcon, "text-error"),
	"database": icon(CpuChipIcon, "text-primary"),
	"design og formgivning": icon(BookmarkIcon, "text-secondary"),
	"detailhandel": icon(ShoppingBagIcon, "text-primary"),
	"detailledelse": icon(ShoppingBagIcon, "text-secondary"),
	"ejendomsmægler": icon(BuildingOfficeIcon, "text-base-content"),
	"ejendomsservice": icon(BuildingOfficeIcon, "text-base-content"),
	"elektriker": icon(BoltIcon, "text-warning"),
	"elektroteknik": icon(BoltIcon, "text-warning"),
	"elev/lærling": icon(AcademicCapIcon, "text-secondary"),
	"finans og forsikring": icon(BanknotesIcon, "text-success"),
	"forskning": icon(BeakerIcon, "text-info"),
	"forsvar og efterretning": icon(ShieldCheckIcon, "text-warning"),
	"freelance": icon(UserCircleIcon, "text-info"),
	"frisør og personlig pleje": icon(HeartIcon, "text-error"),
	"frivillig": icon(HeartIcon, "text-error"),
	"grafisk": icon(DocumentTextIcon, "text-primary"),
	"hotel, restaurant og køkken": icon(ChatBubbleLeftRightIcon, "text-secondary"),
	"indkøb": icon(ShoppingBagIcon, "text-primary"),
	"industriel produktion": icon(WrenchIcon, "text-accent"),
	"institutions- og skoleledelse": icon(AcademicCapIcon, "text-secondary"),
	"internet og www": icon(CpuChipIcon, "text-primary"),
	"it-drift og support": icon(CpuChipIcon, "text-primary"),
	"it-ledelse": icon(PresentationChartLineIcon, "text-primary"),
	"jern og metal": icon(WrenchIcon, "text-primary"),
	"jura": icon(ScaleIcon, "text-warning"),
	"kemi og bioteknik": icon(BeakerIcon, "text-info"),
	"kommunikation og journalistik": icon(MegaphoneIcon, "text-secondary"),
	"kontor": icon(DocumentTextIcon, "text-primary"),
	"kultur og kirke": icon(BookOpenIcon, "text-primary"),
	"lager": icon(TruckIcon, "text-info"),
	"landbrug, skov og fiskeri": icon(PresentationChartLineIcon, "text-success"),
	"ledelse": icon(PresentationChartLineIcon, "text-primary"),
	"ledelse inden for ingeniør og teknik": icon(PresentationChartLineIcon, "text-primary"),
	"logistik og spedition": icon(TruckIcon, "text-info"),
	"læge": icon(HeartIcon, "text-error"),
	"lægesekretær": icon(DocumentTextIcon, "text-primary"),
	"lærer": icon(AcademicCapIcon, "text-secondary"),
	"maling og overfladebehandling": icon(WrenchIcon, "text-primary"),
	"marketing": icon(MegaphoneIcon, "text-secondary"),
	"maskinteknik": icon(WrenchIcon, "text-primary"),
	"medicinal og levnedsmiddel": icon(BeakerIcon, "text-info"),
	"mekanik og auto": icon(WrenchIcon, "text-primary"),
	"nærings- og nydelsesmiddel": icon(ShoppingBagIcon, "text-primary"),
	"offentlig administration": icon(BuildingOfficeIcon, "text-base-content"),
	"oversættelse og sprog": icon(DocumentTextIcon, "text-primary"),
	"personale og hr": icon(UserCircleIcon, "text-info"),
	"pleje og omsorg": icon(HeartIcon, "text-error"),
	"praktikplads": icon(AcademicCapIcon, "text-secondary"),
	"produktions- og procesteknik": icon(WrenchIcon, "text-primary"),
	"projektledelse": icon(PresentationChartLineIcon, "text-primary"),
	"psykologi og psykiatri": icon(HeartIcon, "text-error"),
	"pædagog": icon(AcademicCapIcon, "text-secondary"),
	"rengøring": icon(ShieldCheckIcon, "text-warning"),
	"salg": icon(MegaphoneIcon, "text-secondary"),
	"salgsledelse": icon(PresentationChartLineIcon, "text-primary"),
	"sekretær og reception": icon(DocumentTextIcon, "text-primary"),
	"selvstændig virksomhedsdrift": icon(BriefcaseIcon, "text-base-content"),
	"service": icon(ChatBubbleLeftRightIcon, "text-warning"),
	"sikkerhed": icon(ShieldCheckIcon, "text-warning"),
	"socialrådgivning": icon(HeartIcon, "text-error"),
	"studiejob": icon(AcademicCapIcon, "text-secondary"),
	"sygeplejerske og jordemoder": icon(HeartIcon, "text-error"),
	"systemudvikling og programmering": icon(CpuChipIcon, "text-primary"),
	"tandlæge og klinikpersonale": icon(HeartIcon, "text-error"),
	"teknisk sundhedsarbejde": icon(BeakerIcon, "text-info"),
	"tekstil og kunsthåndværk": icon(BookmarkIcon, "text-secondary"),
	"tele- og datakommunikation": icon(CpuChipIcon, "text-primary"),
	"telemarketing": icon(MegaphoneIcon, "text-secondary"),
	"terapi og genoptræning": icon(HeartIcon, "text-error"),
	"topledelse og bestyrelse": icon(PresentationChartLineIcon, "text-primary"),
	"transport": icon(TruckIcon, "text-info"),
	"træ- og møbelindustri": icon(WrenchIcon, "text-primary"),
	"tømrer og snedker": icon(WrenchIcon, "text-primary"),
	"virksomhedsudvikling": icon(PresentationChartLineIcon, "text-primary"),
	"voksenuddannelse": icon(AcademicCapIcon, "text-secondary"),
	"økonomi og regnskab": icon(BanknotesIcon, "text-success"),
	"økonomi- og virksomhedssystemer": icon(BanknotesIcon, "text-success"),
	"økonomiledelse": icon(BanknotesIcon, "text-success"),
	"øvrige": defaultIcon
};

export const getCategoryIcon = (name?: string | null) => {
	const key = (name ?? "").trim().toLowerCase();
	return categoryIcons[key] ?? defaultIcon;
};
