/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FindjobnuServiceDTOsCvReadabilityResult,
} from '../models/index';
import {
    FindjobnuServiceDTOsCvReadabilityResultFromJSON,
    FindjobnuServiceDTOsCvReadabilityResultToJSON,
} from '../models/index';

export interface AnalyzeCvPdfRequest {
    file: Blob;
}

/**
 * 
 */
export class CVApi extends runtime.BaseAPI {

    /**
     */
    async analyzeCvPdfRaw(requestParameters: AnalyzeCvPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceDTOsCvReadabilityResult>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling analyzeCvPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/cv/analyze`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceDTOsCvReadabilityResultFromJSON(jsonValue));
    }

    /**
     */
    async analyzeCvPdf(requestParameters: AnalyzeCvPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceDTOsCvReadabilityResult> {
        const response = await this.analyzeCvPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
