/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CvReadabilityResult,
} from '../models/index';
import {
    CvReadabilityResultFromJSON,
    CvReadabilityResultToJSON,
} from '../models/index';

export interface AnalyzeCvPdfRequest {
    file?: Blob | null;
}

/**
 * 
 */
export class CVApi extends runtime.BaseAPI {

    /**
     */
    async analyzeCvPdfRaw(requestParameters: AnalyzeCvPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CvReadabilityResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/cv/analyze`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CvReadabilityResultFromJSON(jsonValue));
    }

    /**
     */
    async analyzeCvPdf(requestParameters: AnalyzeCvPdfRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CvReadabilityResult> {
        const response = await this.analyzeCvPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
