/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JobAgentDto,
  JobAgentUpdateRequest,
} from '../models/index';
import {
    JobAgentDtoFromJSON,
    JobAgentDtoToJSON,
    JobAgentUpdateRequestFromJSON,
    JobAgentUpdateRequestToJSON,
} from '../models/index';

export interface CreateOrUpdateJobAgentRequest {
    profileId: number;
    jobAgentUpdateRequest: JobAgentUpdateRequest;
}

export interface GetJobAgentRequest {
    profileId: number;
}

export interface GetJobAgentUnsubscribeLinkRequest {
    profileId: number;
}

export interface UnsubscribeJobAgentRequest {
    token: string;
}

/**
 * 
 */
export class JobAgentApi extends runtime.BaseAPI {

    /**
     */
    async createOrUpdateJobAgentRaw(requestParameters: CreateOrUpdateJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobAgentDto>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling createOrUpdateJobAgent().'
            );
        }

        if (requestParameters['jobAgentUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'jobAgentUpdateRequest',
                'Required parameter "jobAgentUpdateRequest" was null or undefined when calling createOrUpdateJobAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/jobagent/{profileId}`.replace(`{${"profileId"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JobAgentUpdateRequestToJSON(requestParameters['jobAgentUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobAgentDtoFromJSON(jsonValue));
    }

    /**
     */
    async createOrUpdateJobAgent(requestParameters: CreateOrUpdateJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobAgentDto> {
        const response = await this.createOrUpdateJobAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getJobAgentRaw(requestParameters: GetJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobAgentDto>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling getJobAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/jobagent/{profileId}`.replace(`{${"profileId"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobAgentDtoFromJSON(jsonValue));
    }

    /**
     */
    async getJobAgent(requestParameters: GetJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobAgentDto> {
        const response = await this.getJobAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getJobAgentUnsubscribeLinkRaw(requestParameters: GetJobAgentUnsubscribeLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling getJobAgentUnsubscribeLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/jobagent/{profileId}/unsubscribe-link`.replace(`{${"profileId"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async getJobAgentUnsubscribeLink(requestParameters: GetJobAgentUnsubscribeLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getJobAgentUnsubscribeLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async unsubscribeJobAgentRaw(requestParameters: UnsubscribeJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling unsubscribeJobAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/jobagent/unsubscribe/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async unsubscribeJobAgent(requestParameters: UnsubscribeJobAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unsubscribeJobAgentRaw(requestParameters, initOverrides);
    }

}
