/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  NewsletterSubscribeRequest,
  NewsletterSubscribeResponse,
} from '../models/index';
import {
    NewsletterSubscribeRequestFromJSON,
    NewsletterSubscribeRequestToJSON,
    NewsletterSubscribeResponseFromJSON,
    NewsletterSubscribeResponseToJSON,
} from '../models/index';

export interface SubscribeNewsletterRequest {
    newsletterSubscribeRequest: NewsletterSubscribeRequest;
}

/**
 * 
 */
export class NewsletterApi extends runtime.BaseAPI {

    /**
     */
    async subscribeNewsletterRaw(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NewsletterSubscribeResponse>> {
        if (requestParameters['newsletterSubscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'newsletterSubscribeRequest',
                'Required parameter "newsletterSubscribeRequest" was null or undefined when calling subscribeNewsletter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/newsletter/subscribe`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsletterSubscribeRequestToJSON(requestParameters['newsletterSubscribeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NewsletterSubscribeResponseFromJSON(jsonValue));
    }

    /**
     */
    async subscribeNewsletter(requestParameters: SubscribeNewsletterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NewsletterSubscribeResponse> {
        const response = await this.subscribeNewsletterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
