/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FindjobnuServiceDTOsBasicInfoDto,
  FindjobnuServiceDTOsEducationDto,
  FindjobnuServiceDTOsExperienceDto,
  FindjobnuServiceDTOsProfileDto,
  FindjobnuServiceDTOsRequestsProfileCreateRequest,
  FindjobnuServiceDTOsRequestsProfileUpdateRequest,
  FindjobnuServiceDTOsSkillDto,
  FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts,
} from '../models/index';
import {
    FindjobnuServiceDTOsBasicInfoDtoFromJSON,
    FindjobnuServiceDTOsBasicInfoDtoToJSON,
    FindjobnuServiceDTOsEducationDtoFromJSON,
    FindjobnuServiceDTOsEducationDtoToJSON,
    FindjobnuServiceDTOsExperienceDtoFromJSON,
    FindjobnuServiceDTOsExperienceDtoToJSON,
    FindjobnuServiceDTOsProfileDtoFromJSON,
    FindjobnuServiceDTOsProfileDtoToJSON,
    FindjobnuServiceDTOsRequestsProfileCreateRequestFromJSON,
    FindjobnuServiceDTOsRequestsProfileCreateRequestToJSON,
    FindjobnuServiceDTOsRequestsProfileUpdateRequestFromJSON,
    FindjobnuServiceDTOsRequestsProfileUpdateRequestToJSON,
    FindjobnuServiceDTOsSkillDtoFromJSON,
    FindjobnuServiceDTOsSkillDtoToJSON,
    FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsFromJSON,
    FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsToJSON,
} from '../models/index';

export interface CreateProfileRequest {
    findjobnuServiceDTOsRequestsProfileCreateRequest: FindjobnuServiceDTOsRequestsProfileCreateRequest;
}

export interface GetBasicInfoByUserIdRequest {
    userId: string;
}

export interface GetEducationByUserIdRequest {
    userId: string;
}

export interface GetExperienceByUserIdRequest {
    userId: string;
}

export interface GetProfileByUserIdRequest {
    userId: string;
}

export interface GetSavedJobsByUserIdRequest {
    userId: string;
}

export interface GetSkillsByUserIdRequest {
    userId: string;
}

export interface RemoveSavedJobForUserRequest {
    userId: string;
    jobId: string;
}

export interface SaveJobForUserRequest {
    userId: string;
    jobId: string;
}

export interface UpdateProfileRequest {
    id: number;
    findjobnuServiceDTOsRequestsProfileUpdateRequest: FindjobnuServiceDTOsRequestsProfileUpdateRequest;
}

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     */
    async createProfileRaw(requestParameters: CreateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceDTOsProfileDto>> {
        if (requestParameters['findjobnuServiceDTOsRequestsProfileCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'findjobnuServiceDTOsRequestsProfileCreateRequest',
                'Required parameter "findjobnuServiceDTOsRequestsProfileCreateRequest" was null or undefined when calling createProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FindjobnuServiceDTOsRequestsProfileCreateRequestToJSON(requestParameters['findjobnuServiceDTOsRequestsProfileCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceDTOsProfileDtoFromJSON(jsonValue));
    }

    /**
     */
    async createProfile(requestParameters: CreateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceDTOsProfileDto> {
        const response = await this.createProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBasicInfoByUserIdRaw(requestParameters: GetBasicInfoByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceDTOsBasicInfoDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getBasicInfoByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/basicinfo`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceDTOsBasicInfoDtoFromJSON(jsonValue));
    }

    /**
     */
    async getBasicInfoByUserId(requestParameters: GetBasicInfoByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceDTOsBasicInfoDto> {
        const response = await this.getBasicInfoByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getEducationByUserIdRaw(requestParameters: GetEducationByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FindjobnuServiceDTOsEducationDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getEducationByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/education`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FindjobnuServiceDTOsEducationDtoFromJSON));
    }

    /**
     */
    async getEducationByUserId(requestParameters: GetEducationByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FindjobnuServiceDTOsEducationDto>> {
        const response = await this.getEducationByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getExperienceByUserIdRaw(requestParameters: GetExperienceByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FindjobnuServiceDTOsExperienceDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getExperienceByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/experience`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FindjobnuServiceDTOsExperienceDtoFromJSON));
    }

    /**
     */
    async getExperienceByUserId(requestParameters: GetExperienceByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FindjobnuServiceDTOsExperienceDto>> {
        const response = await this.getExperienceByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProfileByUserIdRaw(requestParameters: GetProfileByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceDTOsProfileDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getProfileByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceDTOsProfileDtoFromJSON(jsonValue));
    }

    /**
     */
    async getProfileByUserId(requestParameters: GetProfileByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceDTOsProfileDto> {
        const response = await this.getProfileByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSavedJobsByUserIdRaw(requestParameters: GetSavedJobsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getSavedJobsByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/savedjobs`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsFromJSON(jsonValue));
    }

    /**
     */
    async getSavedJobsByUserId(requestParameters: GetSavedJobsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts> {
        const response = await this.getSavedJobsByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSkillsByUserIdRaw(requestParameters: GetSkillsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FindjobnuServiceDTOsSkillDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getSkillsByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/skills`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FindjobnuServiceDTOsSkillDtoFromJSON));
    }

    /**
     */
    async getSkillsByUserId(requestParameters: GetSkillsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FindjobnuServiceDTOsSkillDto>> {
        const response = await this.getSkillsByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async importLinkedInProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FindjobnuServiceDTOsProfileDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/linkedin/import`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FindjobnuServiceDTOsProfileDtoFromJSON(jsonValue));
    }

    /**
     */
    async importLinkedInProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FindjobnuServiceDTOsProfileDto> {
        const response = await this.importLinkedInProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async removeSavedJobForUserRaw(requestParameters: RemoveSavedJobForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeSavedJobForUser().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling removeSavedJobForUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/savedjobs/{jobId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async removeSavedJobForUser(requestParameters: RemoveSavedJobForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removeSavedJobForUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async saveJobForUserRaw(requestParameters: SaveJobForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling saveJobForUser().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling saveJobForUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{userId}/savedjobs/{jobId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async saveJobForUser(requestParameters: SaveJobForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.saveJobForUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateProfileRaw(requestParameters: UpdateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProfile().'
            );
        }

        if (requestParameters['findjobnuServiceDTOsRequestsProfileUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'findjobnuServiceDTOsRequestsProfileUpdateRequest',
                'Required parameter "findjobnuServiceDTOsRequestsProfileUpdateRequest" was null or undefined when calling updateProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/profile/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: FindjobnuServiceDTOsRequestsProfileUpdateRequestToJSON(requestParameters['findjobnuServiceDTOsRequestsProfileUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateProfile(requestParameters: UpdateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateProfileRaw(requestParameters, initOverrides);
    }

}
