/* tslint:disable */
/* eslint-disable */
/**
 * findjobnuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccomplishmentDto
 */
export interface AccomplishmentDto {
    /**
     * 
     * @type {number}
     * @memberof AccomplishmentDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccomplishmentDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccomplishmentDto
     */
    title?: string | null;
}

/**
 * Check if a given object implements the AccomplishmentDto interface.
 */
export function instanceOfAccomplishmentDto(value: object): value is AccomplishmentDto {
    return true;
}

export function AccomplishmentDtoFromJSON(json: any): AccomplishmentDto {
    return AccomplishmentDtoFromJSONTyped(json, false);
}

export function AccomplishmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccomplishmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AccomplishmentDtoToJSON(json: any): AccomplishmentDto {
    return AccomplishmentDtoToJSONTyped(json, false);
}

export function AccomplishmentDtoToJSONTyped(value?: AccomplishmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'title': value['title'],
    };
}

