/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface Accomplishment
 */
export interface Accomplishment {
    /**
     * 
     * @type {number}
     * @memberof Accomplishment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Accomplishment
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Accomplishment
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Accomplishment
     */
    profileId?: number;
    /**
     * 
     * @type {Profile}
     * @memberof Accomplishment
     */
    profile?: Profile;
}

/**
 * Check if a given object implements the Accomplishment interface.
 */
export function instanceOfAccomplishment(value: object): value is Accomplishment {
    return true;
}

export function AccomplishmentFromJSON(json: any): Accomplishment {
    return AccomplishmentFromJSONTyped(json, false);
}

export function AccomplishmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Accomplishment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'title': json['title'] == null ? undefined : json['title'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : ProfileFromJSON(json['profile']),
    };
}

export function AccomplishmentToJSON(json: any): Accomplishment {
    return AccomplishmentToJSONTyped(json, false);
}

export function AccomplishmentToJSONTyped(value?: Accomplishment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'title': value['title'],
        'profileId': value['profileId'],
        'profile': ProfileToJSON(value['profile']),
    };
}

