/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccomplishmentUpdate
 */
export interface AccomplishmentUpdate {
    /**
     * 
     * @type {string}
     * @memberof AccomplishmentUpdate
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccomplishmentUpdate
     */
    title?: string | null;
}

/**
 * Check if a given object implements the AccomplishmentUpdate interface.
 */
export function instanceOfAccomplishmentUpdate(value: object): value is AccomplishmentUpdate {
    return true;
}

export function AccomplishmentUpdateFromJSON(json: any): AccomplishmentUpdate {
    return AccomplishmentUpdateFromJSONTyped(json, false);
}

export function AccomplishmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccomplishmentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AccomplishmentUpdateToJSON(json: any): AccomplishmentUpdate {
    return AccomplishmentUpdateToJSONTyped(json, false);
}

export function AccomplishmentUpdateToJSONTyped(value?: AccomplishmentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'title': value['title'],
    };
}

