/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryJobCountResponse } from './CategoryJobCountResponse';
import {
    CategoryJobCountResponseFromJSON,
    CategoryJobCountResponseFromJSONTyped,
    CategoryJobCountResponseToJSON,
    CategoryJobCountResponseToJSONTyped,
} from './CategoryJobCountResponse';

/**
 * 
 * @export
 * @interface CategoriesResponse
 */
export interface CategoriesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CategoriesResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CategoriesResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Array<CategoryJobCountResponse>}
     * @memberof CategoriesResponse
     */
    categories?: Array<CategoryJobCountResponse> | null;
}

/**
 * Check if a given object implements the CategoriesResponse interface.
 */
export function instanceOfCategoriesResponse(value: object): value is CategoriesResponse {
    return true;
}

export function CategoriesResponseFromJSON(json: any): CategoriesResponse {
    return CategoriesResponseFromJSONTyped(json, false);
}

export function CategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryJobCountResponseFromJSON)),
    };
}

export function CategoriesResponseToJSON(json: any): CategoriesResponse {
    return CategoriesResponseToJSONTyped(json, false);
}

export function CategoriesResponseToJSONTyped(value?: CategoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryJobCountResponseToJSON)),
    };
}

