/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityResponse
 */
export interface CityResponse {
    /**
     * 
     * @type {number}
     * @memberof CityResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CityResponse
     */
    cityName?: string | null;
}

/**
 * Check if a given object implements the CityResponse interface.
 */
export function instanceOfCityResponse(value: object): value is CityResponse {
    return true;
}

export function CityResponseFromJSON(json: any): CityResponse {
    return CityResponseFromJSONTyped(json, false);
}

export function CityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'cityName': json['cityName'] == null ? undefined : json['cityName'],
    };
}

export function CityResponseToJSON(json: any): CityResponse {
    return CityResponseToJSONTyped(json, false);
}

export function CityResponseToJSONTyped(value?: CityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cityName': value['cityName'],
    };
}

