/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactDto
 */
export interface ContactDto {
    /**
     * 
     * @type {number}
     * @memberof ContactDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    url?: string | null;
}

/**
 * Check if a given object implements the ContactDto interface.
 */
export function instanceOfContactDto(value: object): value is ContactDto {
    return true;
}

export function ContactDtoFromJSON(json: any): ContactDto {
    return ContactDtoFromJSONTyped(json, false);
}

export function ContactDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ContactDtoToJSON(json: any): ContactDto {
    return ContactDtoToJSONTyped(json, false);
}

export function ContactDtoToJSONTyped(value?: ContactDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'occupation': value['occupation'],
        'url': value['url'],
    };
}

