/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CvReadabilitySummary } from './CvReadabilitySummary';
import {
    CvReadabilitySummaryFromJSON,
    CvReadabilitySummaryFromJSONTyped,
    CvReadabilitySummaryToJSON,
    CvReadabilitySummaryToJSONTyped,
} from './CvReadabilitySummary';

/**
 * 
 * @export
 * @interface CvReadabilityResult
 */
export interface CvReadabilityResult {
    /**
     * 
     * @type {string}
     * @memberof CvReadabilityResult
     */
    extractedText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CvReadabilityResult
     */
    readabilityScore?: number;
    /**
     * 
     * @type {CvReadabilitySummary}
     * @memberof CvReadabilityResult
     */
    summary?: CvReadabilitySummary;
}

/**
 * Check if a given object implements the CvReadabilityResult interface.
 */
export function instanceOfCvReadabilityResult(value: object): value is CvReadabilityResult {
    return true;
}

export function CvReadabilityResultFromJSON(json: any): CvReadabilityResult {
    return CvReadabilityResultFromJSONTyped(json, false);
}

export function CvReadabilityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvReadabilityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'extractedText': json['extractedText'] == null ? undefined : json['extractedText'],
        'readabilityScore': json['readabilityScore'] == null ? undefined : json['readabilityScore'],
        'summary': json['summary'] == null ? undefined : CvReadabilitySummaryFromJSON(json['summary']),
    };
}

export function CvReadabilityResultToJSON(json: any): CvReadabilityResult {
    return CvReadabilityResultToJSONTyped(json, false);
}

export function CvReadabilityResultToJSONTyped(value?: CvReadabilityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extractedText': value['extractedText'],
        'readabilityScore': value['readabilityScore'],
        'summary': CvReadabilitySummaryToJSON(value['summary']),
    };
}

