/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EducationUpdate
 */
export interface EducationUpdate {
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    institution?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    degree?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdate
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the EducationUpdate interface.
 */
export function instanceOfEducationUpdate(value: object): value is EducationUpdate {
    return true;
}

export function EducationUpdateFromJSON(json: any): EducationUpdate {
    return EducationUpdateFromJSONTyped(json, false);
}

export function EducationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'institution': json['institution'] == null ? undefined : json['institution'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function EducationUpdateToJSON(json: any): EducationUpdate {
    return EducationUpdateToJSONTyped(json, false);
}

export function EducationUpdateToJSONTyped(value?: EducationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'institution': value['institution'],
        'degree': value['degree'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

