/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EducationDto
 */
export interface EducationDto {
    /**
     * 
     * @type {number}
     * @memberof EducationDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    institution?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    degree?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EducationDto
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the EducationDto interface.
 */
export function instanceOfEducationDto(value: object): value is EducationDto {
    return true;
}

export function EducationDtoFromJSON(json: any): EducationDto {
    return EducationDtoFromJSONTyped(json, false);
}

export function EducationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function EducationDtoToJSON(json: any): EducationDto {
    return EducationDtoToJSONTyped(json, false);
}

export function EducationDtoToJSONTyped(value?: EducationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'institution': value['institution'],
        'degree': value['degree'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

