/* tslint:disable */
/* eslint-disable */
/**
 * findjobnuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperienceDto
 */
export interface ExperienceDto {
    /**
     * 
     * @type {number}
     * @memberof ExperienceDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    positionTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceDto
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the ExperienceDto interface.
 */
export function instanceOfExperienceDto(value: object): value is ExperienceDto {
    return true;
}

export function ExperienceDtoFromJSON(json: any): ExperienceDto {
    return ExperienceDtoFromJSONTyped(json, false);
}

export function ExperienceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperienceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'positionTitle': json['positionTitle'] == null ? undefined : json['positionTitle'],
        'company': json['company'] == null ? undefined : json['company'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'location': json['location'] == null ? undefined : json['location'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function ExperienceDtoToJSON(json: any): ExperienceDto {
    return ExperienceDtoToJSONTyped(json, false);
}

export function ExperienceDtoToJSONTyped(value?: ExperienceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'positionTitle': value['positionTitle'],
        'company': value['company'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'duration': value['duration'],
        'location': value['location'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

