/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExperienceUpdate
 */
export interface ExperienceUpdate {
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    positionTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExperienceUpdate
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the ExperienceUpdate interface.
 */
export function instanceOfExperienceUpdate(value: object): value is ExperienceUpdate {
    return true;
}

export function ExperienceUpdateFromJSON(json: any): ExperienceUpdate {
    return ExperienceUpdateFromJSONTyped(json, false);
}

export function ExperienceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExperienceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'positionTitle': json['positionTitle'] == null ? undefined : json['positionTitle'],
        'company': json['company'] == null ? undefined : json['company'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'location': json['location'] == null ? undefined : json['location'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function ExperienceUpdateToJSON(json: any): ExperienceUpdate {
    return ExperienceUpdateToJSONTyped(json, false);
}

export function ExperienceUpdateToJSONTyped(value?: ExperienceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'positionTitle': value['positionTitle'],
        'company': value['company'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'duration': value['duration'],
        'location': value['location'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

