/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceDTOsResponsesJobIndexPostResponse } from './FindjobnuServiceDTOsResponsesJobIndexPostResponse';
import {
    FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped,
} from './FindjobnuServiceDTOsResponsesJobIndexPostResponse';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull
 */
export interface FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull {
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsResponsesJobIndexPostResponse>}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull
     */
    items?: Array<FindjobnuServiceDTOsResponsesJobIndexPostResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull interface.
 */
export function instanceOfFindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull(value: object): value is FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull {
    return true;
}

export function FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullFromJSON(json: any): FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull {
    return FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullToJSON(json: any): FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull {
    return FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennullToJSONTyped(value?: FindjobnuServiceDTOsResponsesPagedResponse1FindjobnuServiceDTOsResponsesJobIndexPostResponse FindjobnuService Version1000 Cultureneutral PublicKeyTokennull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
    };
}

