/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsContact } from './FindjobnuServiceModelsContact';
import {
    FindjobnuServiceModelsContactFromJSON,
    FindjobnuServiceModelsContactFromJSONTyped,
    FindjobnuServiceModelsContactToJSON,
    FindjobnuServiceModelsContactToJSONTyped,
} from './FindjobnuServiceModelsContact';
import type { FindjobnuServiceModelsSkill } from './FindjobnuServiceModelsSkill';
import {
    FindjobnuServiceModelsSkillFromJSON,
    FindjobnuServiceModelsSkillFromJSONTyped,
    FindjobnuServiceModelsSkillToJSON,
    FindjobnuServiceModelsSkillToJSONTyped,
} from './FindjobnuServiceModelsSkill';
import type { FindjobnuServiceModelsAccomplishment } from './FindjobnuServiceModelsAccomplishment';
import {
    FindjobnuServiceModelsAccomplishmentFromJSON,
    FindjobnuServiceModelsAccomplishmentFromJSONTyped,
    FindjobnuServiceModelsAccomplishmentToJSON,
    FindjobnuServiceModelsAccomplishmentToJSONTyped,
} from './FindjobnuServiceModelsAccomplishment';
import type { FindjobnuServiceModelsJobAgent } from './FindjobnuServiceModelsJobAgent';
import {
    FindjobnuServiceModelsJobAgentFromJSON,
    FindjobnuServiceModelsJobAgentFromJSONTyped,
    FindjobnuServiceModelsJobAgentToJSON,
    FindjobnuServiceModelsJobAgentToJSONTyped,
} from './FindjobnuServiceModelsJobAgent';
import type { FindjobnuServiceModelsExperience } from './FindjobnuServiceModelsExperience';
import {
    FindjobnuServiceModelsExperienceFromJSON,
    FindjobnuServiceModelsExperienceFromJSONTyped,
    FindjobnuServiceModelsExperienceToJSON,
    FindjobnuServiceModelsExperienceToJSONTyped,
} from './FindjobnuServiceModelsExperience';
import type { FindjobnuServiceModelsInterest } from './FindjobnuServiceModelsInterest';
import {
    FindjobnuServiceModelsInterestFromJSON,
    FindjobnuServiceModelsInterestFromJSONTyped,
    FindjobnuServiceModelsInterestToJSON,
    FindjobnuServiceModelsInterestToJSONTyped,
} from './FindjobnuServiceModelsInterest';
import type { FindjobnuServiceModelsBasicInfo } from './FindjobnuServiceModelsBasicInfo';
import {
    FindjobnuServiceModelsBasicInfoFromJSON,
    FindjobnuServiceModelsBasicInfoFromJSONTyped,
    FindjobnuServiceModelsBasicInfoToJSON,
    FindjobnuServiceModelsBasicInfoToJSONTyped,
} from './FindjobnuServiceModelsBasicInfo';
import type { FindjobnuServiceModelsEducation } from './FindjobnuServiceModelsEducation';
import {
    FindjobnuServiceModelsEducationFromJSON,
    FindjobnuServiceModelsEducationFromJSONTyped,
    FindjobnuServiceModelsEducationToJSON,
    FindjobnuServiceModelsEducationToJSONTyped,
} from './FindjobnuServiceModelsEducation';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsProfile
 */
export interface FindjobnuServiceModelsProfile {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsProfile
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsProfile
     */
    userId: string;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsProfile
     */
    lastUpdatedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsProfile
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceModelsProfile
     */
    savedJobPosts?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceModelsProfile
     */
    keywords?: Array<string> | null;
    /**
     * 
     * @type {FindjobnuServiceModelsBasicInfo}
     * @memberof FindjobnuServiceModelsProfile
     */
    basicInfo: FindjobnuServiceModelsBasicInfo;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsExperience>}
     * @memberof FindjobnuServiceModelsProfile
     */
    experiences?: Array<FindjobnuServiceModelsExperience> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsEducation>}
     * @memberof FindjobnuServiceModelsProfile
     */
    educations?: Array<FindjobnuServiceModelsEducation> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsInterest>}
     * @memberof FindjobnuServiceModelsProfile
     */
    interests?: Array<FindjobnuServiceModelsInterest> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsAccomplishment>}
     * @memberof FindjobnuServiceModelsProfile
     */
    accomplishments?: Array<FindjobnuServiceModelsAccomplishment> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsContact>}
     * @memberof FindjobnuServiceModelsProfile
     */
    contacts?: Array<FindjobnuServiceModelsContact> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsSkill>}
     * @memberof FindjobnuServiceModelsProfile
     */
    skills?: Array<FindjobnuServiceModelsSkill> | null;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceModelsProfile
     */
    hasJobAgent?: boolean;
    /**
     * 
     * @type {FindjobnuServiceModelsJobAgent}
     * @memberof FindjobnuServiceModelsProfile
     */
    jobAgent?: FindjobnuServiceModelsJobAgent;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsProfile interface.
 */
export function instanceOfFindjobnuServiceModelsProfile(value: object): value is FindjobnuServiceModelsProfile {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('basicInfo' in value) || value['basicInfo'] === undefined) return false;
    return true;
}

export function FindjobnuServiceModelsProfileFromJSON(json: any): FindjobnuServiceModelsProfile {
    return FindjobnuServiceModelsProfileFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'],
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'savedJobPosts': json['savedJobPosts'] == null ? undefined : json['savedJobPosts'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'basicInfo': FindjobnuServiceModelsBasicInfoFromJSON(json['basicInfo']),
        'experiences': json['experiences'] == null ? undefined : ((json['experiences'] as Array<any>).map(FindjobnuServiceModelsExperienceFromJSON)),
        'educations': json['educations'] == null ? undefined : ((json['educations'] as Array<any>).map(FindjobnuServiceModelsEducationFromJSON)),
        'interests': json['interests'] == null ? undefined : ((json['interests'] as Array<any>).map(FindjobnuServiceModelsInterestFromJSON)),
        'accomplishments': json['accomplishments'] == null ? undefined : ((json['accomplishments'] as Array<any>).map(FindjobnuServiceModelsAccomplishmentFromJSON)),
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(FindjobnuServiceModelsContactFromJSON)),
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(FindjobnuServiceModelsSkillFromJSON)),
        'hasJobAgent': json['hasJobAgent'] == null ? undefined : json['hasJobAgent'],
        'jobAgent': json['jobAgent'] == null ? undefined : FindjobnuServiceModelsJobAgentFromJSON(json['jobAgent']),
    };
}

export function FindjobnuServiceModelsProfileToJSON(json: any): FindjobnuServiceModelsProfile {
    return FindjobnuServiceModelsProfileToJSONTyped(json, false);
}

export function FindjobnuServiceModelsProfileToJSONTyped(value?: FindjobnuServiceModelsProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'savedJobPosts': value['savedJobPosts'],
        'keywords': value['keywords'],
        'basicInfo': FindjobnuServiceModelsBasicInfoToJSON(value['basicInfo']),
        'experiences': value['experiences'] == null ? undefined : ((value['experiences'] as Array<any>).map(FindjobnuServiceModelsExperienceToJSON)),
        'educations': value['educations'] == null ? undefined : ((value['educations'] as Array<any>).map(FindjobnuServiceModelsEducationToJSON)),
        'interests': value['interests'] == null ? undefined : ((value['interests'] as Array<any>).map(FindjobnuServiceModelsInterestToJSON)),
        'accomplishments': value['accomplishments'] == null ? undefined : ((value['accomplishments'] as Array<any>).map(FindjobnuServiceModelsAccomplishmentToJSON)),
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(FindjobnuServiceModelsContactToJSON)),
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(FindjobnuServiceModelsSkillToJSON)),
        'hasJobAgent': value['hasJobAgent'],
        'jobAgent': FindjobnuServiceModelsJobAgentToJSON(value['jobAgent']),
    };
}

