/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';
import type { FindjobnuServiceModelsJobAgentFrequency } from './FindjobnuServiceModelsJobAgentFrequency';
import {
    FindjobnuServiceModelsJobAgentFrequencyFromJSON,
    FindjobnuServiceModelsJobAgentFrequencyFromJSONTyped,
    FindjobnuServiceModelsJobAgentFrequencyToJSON,
    FindjobnuServiceModelsJobAgentFrequencyToJSONTyped,
} from './FindjobnuServiceModelsJobAgentFrequency';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsJobAgent
 */
export interface FindjobnuServiceModelsJobAgent {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    profile?: FindjobnuServiceModelsProfile;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    enabled?: boolean;
    /**
     * 
     * @type {FindjobnuServiceModelsJobAgentFrequency}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    frequency?: FindjobnuServiceModelsJobAgentFrequency;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    lastSentAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    nextSendAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobAgent
     */
    unsubscribeToken?: string | null;
}



/**
 * Check if a given object implements the FindjobnuServiceModelsJobAgent interface.
 */
export function instanceOfFindjobnuServiceModelsJobAgent(value: object): value is FindjobnuServiceModelsJobAgent {
    return true;
}

export function FindjobnuServiceModelsJobAgentFromJSON(json: any): FindjobnuServiceModelsJobAgent {
    return FindjobnuServiceModelsJobAgentFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsJobAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsJobAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'frequency': json['frequency'] == null ? undefined : FindjobnuServiceModelsJobAgentFrequencyFromJSON(json['frequency']),
        'lastSentAt': json['lastSentAt'] == null ? undefined : (new Date(json['lastSentAt'])),
        'nextSendAt': json['nextSendAt'] == null ? undefined : (new Date(json['nextSendAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'unsubscribeToken': json['unsubscribeToken'] == null ? undefined : json['unsubscribeToken'],
    };
}

export function FindjobnuServiceModelsJobAgentToJSON(json: any): FindjobnuServiceModelsJobAgent {
    return FindjobnuServiceModelsJobAgentToJSONTyped(json, false);
}

export function FindjobnuServiceModelsJobAgentToJSONTyped(value?: FindjobnuServiceModelsJobAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
        'enabled': value['enabled'],
        'frequency': FindjobnuServiceModelsJobAgentFrequencyToJSON(value['frequency']),
        'lastSentAt': value['lastSentAt'] == null ? undefined : ((value['lastSentAt'] as any).toISOString()),
        'nextSendAt': value['nextSendAt'] == null ? undefined : ((value['nextSendAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'unsubscribeToken': value['unsubscribeToken'],
    };
}

