/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsProfileCreateRequest
 */
export interface FindjobnuServiceDTOsRequestsProfileCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileCreateRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileCreateRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileCreateRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileCreateRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileCreateRequest
     */
    summary?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsProfileCreateRequest interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsProfileCreateRequest(value: object): value is FindjobnuServiceDTOsRequestsProfileCreateRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function FindjobnuServiceDTOsRequestsProfileCreateRequestFromJSON(json: any): FindjobnuServiceDTOsRequestsProfileCreateRequest {
    return FindjobnuServiceDTOsRequestsProfileCreateRequestFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsProfileCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsProfileCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'fullName': json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function FindjobnuServiceDTOsRequestsProfileCreateRequestToJSON(json: any): FindjobnuServiceDTOsRequestsProfileCreateRequest {
    return FindjobnuServiceDTOsRequestsProfileCreateRequestToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsProfileCreateRequestToJSONTyped(value?: FindjobnuServiceDTOsRequestsProfileCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'fullName': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'summary': value['summary'],
    };
}

