/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FindjobnuServiceModelsJobAgentFrequency = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type FindjobnuServiceModelsJobAgentFrequency = typeof FindjobnuServiceModelsJobAgentFrequency[keyof typeof FindjobnuServiceModelsJobAgentFrequency];


export function instanceOfFindjobnuServiceModelsJobAgentFrequency(value: any): boolean {
    for (const key in FindjobnuServiceModelsJobAgentFrequency) {
        if (Object.prototype.hasOwnProperty.call(FindjobnuServiceModelsJobAgentFrequency, key)) {
            if (FindjobnuServiceModelsJobAgentFrequency[key as keyof typeof FindjobnuServiceModelsJobAgentFrequency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FindjobnuServiceModelsJobAgentFrequencyFromJSON(json: any): FindjobnuServiceModelsJobAgentFrequency {
    return FindjobnuServiceModelsJobAgentFrequencyFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsJobAgentFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsJobAgentFrequency {
    return json as FindjobnuServiceModelsJobAgentFrequency;
}

export function FindjobnuServiceModelsJobAgentFrequencyToJSON(value?: FindjobnuServiceModelsJobAgentFrequency | null): any {
    return value as any;
}

export function FindjobnuServiceModelsJobAgentFrequencyToJSONTyped(value: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsJobAgentFrequency {
    return value as FindjobnuServiceModelsJobAgentFrequency;
}

