/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FindjobnuServiceModelsSkillProficiency = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type FindjobnuServiceModelsSkillProficiency = typeof FindjobnuServiceModelsSkillProficiency[keyof typeof FindjobnuServiceModelsSkillProficiency];


export function instanceOfFindjobnuServiceModelsSkillProficiency(value: any): boolean {
    for (const key in FindjobnuServiceModelsSkillProficiency) {
        if (Object.prototype.hasOwnProperty.call(FindjobnuServiceModelsSkillProficiency, key)) {
            if (FindjobnuServiceModelsSkillProficiency[key as keyof typeof FindjobnuServiceModelsSkillProficiency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FindjobnuServiceModelsSkillProficiencyFromJSON(json: any): FindjobnuServiceModelsSkillProficiency {
    return FindjobnuServiceModelsSkillProficiencyFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsSkillProficiencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsSkillProficiency {
    return json as FindjobnuServiceModelsSkillProficiency;
}

export function FindjobnuServiceModelsSkillProficiencyToJSON(value?: FindjobnuServiceModelsSkillProficiency | null): any {
    return value as any;
}

export function FindjobnuServiceModelsSkillProficiencyToJSONTyped(value: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsSkillProficiency {
    return value as FindjobnuServiceModelsSkillProficiency;
}

