/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsSkillDto
 */
export interface FindjobnuServiceDTOsSkillDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsSkillDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsSkillDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsSkillDto
     */
    proficiency?: number;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsSkillDto interface.
 */
export function instanceOfFindjobnuServiceDTOsSkillDto(value: object): value is FindjobnuServiceDTOsSkillDto {
    return true;
}

export function FindjobnuServiceDTOsSkillDtoFromJSON(json: any): FindjobnuServiceDTOsSkillDto {
    return FindjobnuServiceDTOsSkillDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsSkillDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsSkillDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'proficiency': json['proficiency'] == null ? undefined : json['proficiency'],
    };
}

export function FindjobnuServiceDTOsSkillDtoToJSON(json: any): FindjobnuServiceDTOsSkillDto {
    return FindjobnuServiceDTOsSkillDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsSkillDtoToJSONTyped(value?: FindjobnuServiceDTOsSkillDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'proficiency': value['proficiency'],
    };
}

