/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsCvReadabilitySummary
 */
export interface FindjobnuServiceDTOsCvReadabilitySummary {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    totalChars?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    totalWords?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    totalLines?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    hasEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    hasPhone?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    bulletCount?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    matchedSections?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    totalSectionKeywords?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsCvReadabilitySummary
     */
    note?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsCvReadabilitySummary interface.
 */
export function instanceOfFindjobnuServiceDTOsCvReadabilitySummary(value: object): value is FindjobnuServiceDTOsCvReadabilitySummary {
    return true;
}

export function FindjobnuServiceDTOsCvReadabilitySummaryFromJSON(json: any): FindjobnuServiceDTOsCvReadabilitySummary {
    return FindjobnuServiceDTOsCvReadabilitySummaryFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsCvReadabilitySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsCvReadabilitySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalChars': json['totalChars'] == null ? undefined : json['totalChars'],
        'totalWords': json['totalWords'] == null ? undefined : json['totalWords'],
        'totalLines': json['totalLines'] == null ? undefined : json['totalLines'],
        'hasEmail': json['hasEmail'] == null ? undefined : json['hasEmail'],
        'hasPhone': json['hasPhone'] == null ? undefined : json['hasPhone'],
        'bulletCount': json['bulletCount'] == null ? undefined : json['bulletCount'],
        'matchedSections': json['matchedSections'] == null ? undefined : json['matchedSections'],
        'totalSectionKeywords': json['totalSectionKeywords'] == null ? undefined : json['totalSectionKeywords'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function FindjobnuServiceDTOsCvReadabilitySummaryToJSON(json: any): FindjobnuServiceDTOsCvReadabilitySummary {
    return FindjobnuServiceDTOsCvReadabilitySummaryToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsCvReadabilitySummaryToJSONTyped(value?: FindjobnuServiceDTOsCvReadabilitySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalChars': value['totalChars'],
        'totalWords': value['totalWords'],
        'totalLines': value['totalLines'],
        'hasEmail': value['hasEmail'],
        'hasPhone': value['hasPhone'],
        'bulletCount': value['bulletCount'],
        'matchedSections': value['matchedSections'],
        'totalSectionKeywords': value['totalSectionKeywords'],
        'note': value['note'],
    };
}

