/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsContactDto
 */
export interface FindjobnuServiceDTOsContactDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsContactDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsContactDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsContactDto
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsContactDto
     */
    url?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsContactDto interface.
 */
export function instanceOfFindjobnuServiceDTOsContactDto(value: object): value is FindjobnuServiceDTOsContactDto {
    return true;
}

export function FindjobnuServiceDTOsContactDtoFromJSON(json: any): FindjobnuServiceDTOsContactDto {
    return FindjobnuServiceDTOsContactDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsContactDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsContactDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function FindjobnuServiceDTOsContactDtoToJSON(json: any): FindjobnuServiceDTOsContactDto {
    return FindjobnuServiceDTOsContactDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsContactDtoToJSONTyped(value?: FindjobnuServiceDTOsContactDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'occupation': value['occupation'],
        'url': value['url'],
    };
}

