/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsEducationUpdate
 */
export interface FindjobnuServiceDTOsRequestsEducationUpdate {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    institution?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    degree?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsEducationUpdate
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsEducationUpdate interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsEducationUpdate(value: object): value is FindjobnuServiceDTOsRequestsEducationUpdate {
    return true;
}

export function FindjobnuServiceDTOsRequestsEducationUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsEducationUpdate {
    return FindjobnuServiceDTOsRequestsEducationUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsEducationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsEducationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'institution': json['institution'] == null ? undefined : json['institution'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function FindjobnuServiceDTOsRequestsEducationUpdateToJSON(json: any): FindjobnuServiceDTOsRequestsEducationUpdate {
    return FindjobnuServiceDTOsRequestsEducationUpdateToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsEducationUpdateToJSONTyped(value?: FindjobnuServiceDTOsRequestsEducationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'institution': value['institution'],
        'degree': value['degree'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

