/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceModelsBasicInfo
 */
export interface FindjobnuServiceModelsBasicInfo {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    about?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceModelsBasicInfo
     */
    openToWork?: boolean;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsBasicInfo interface.
 */
export function instanceOfFindjobnuServiceModelsBasicInfo(value: object): value is FindjobnuServiceModelsBasicInfo {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function FindjobnuServiceModelsBasicInfoFromJSON(json: any): FindjobnuServiceModelsBasicInfo {
    return FindjobnuServiceModelsBasicInfoFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsBasicInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsBasicInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'about': json['about'] == null ? undefined : json['about'],
        'location': json['location'] == null ? undefined : json['location'],
        'company': json['company'] == null ? undefined : json['company'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'openToWork': json['openToWork'] == null ? undefined : json['openToWork'],
    };
}

export function FindjobnuServiceModelsBasicInfoToJSON(json: any): FindjobnuServiceModelsBasicInfo {
    return FindjobnuServiceModelsBasicInfoToJSONTyped(json, false);
}

export function FindjobnuServiceModelsBasicInfoToJSONTyped(value?: FindjobnuServiceModelsBasicInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'dateOfBirth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth'] as any).toISOString()),
        'phoneNumber': value['phoneNumber'],
        'about': value['about'],
        'location': value['location'],
        'company': value['company'],
        'jobTitle': value['jobTitle'],
        'linkedinUrl': value['linkedinUrl'],
        'openToWork': value['openToWork'],
    };
}

