/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsResponsesCityResponse
 */
export interface FindjobnuServiceDTOsResponsesCityResponse {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesCityResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesCityResponse
     */
    cityName?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsResponsesCityResponse interface.
 */
export function instanceOfFindjobnuServiceDTOsResponsesCityResponse(value: object): value is FindjobnuServiceDTOsResponsesCityResponse {
    return true;
}

export function FindjobnuServiceDTOsResponsesCityResponseFromJSON(json: any): FindjobnuServiceDTOsResponsesCityResponse {
    return FindjobnuServiceDTOsResponsesCityResponseFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesCityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsResponsesCityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'cityName': json['cityName'] == null ? undefined : json['cityName'],
    };
}

export function FindjobnuServiceDTOsResponsesCityResponseToJSON(json: any): FindjobnuServiceDTOsResponsesCityResponse {
    return FindjobnuServiceDTOsResponsesCityResponseToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesCityResponseToJSONTyped(value?: FindjobnuServiceDTOsResponsesCityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cityName': value['cityName'],
    };
}

