/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsExperienceDto
 */
export interface FindjobnuServiceDTOsExperienceDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    positionTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsExperienceDto
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsExperienceDto interface.
 */
export function instanceOfFindjobnuServiceDTOsExperienceDto(value: object): value is FindjobnuServiceDTOsExperienceDto {
    return true;
}

export function FindjobnuServiceDTOsExperienceDtoFromJSON(json: any): FindjobnuServiceDTOsExperienceDto {
    return FindjobnuServiceDTOsExperienceDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsExperienceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsExperienceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'positionTitle': json['positionTitle'] == null ? undefined : json['positionTitle'],
        'company': json['company'] == null ? undefined : json['company'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'location': json['location'] == null ? undefined : json['location'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function FindjobnuServiceDTOsExperienceDtoToJSON(json: any): FindjobnuServiceDTOsExperienceDto {
    return FindjobnuServiceDTOsExperienceDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsExperienceDtoToJSONTyped(value?: FindjobnuServiceDTOsExperienceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'positionTitle': value['positionTitle'],
        'company': value['company'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'duration': value['duration'],
        'location': value['location'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

