/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceDTOsRequestsSkillProficiencyUpdate } from './FindjobnuServiceDTOsRequestsSkillProficiencyUpdate';
import {
    FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSON,
    FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSONTyped,
    FindjobnuServiceDTOsRequestsSkillProficiencyUpdateToJSON,
    FindjobnuServiceDTOsRequestsSkillProficiencyUpdateToJSONTyped,
} from './FindjobnuServiceDTOsRequestsSkillProficiencyUpdate';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsSkillUpdate
 */
export interface FindjobnuServiceDTOsRequestsSkillUpdate {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsSkillUpdate
     */
    name: string;
    /**
     * 
     * @type {FindjobnuServiceDTOsRequestsSkillProficiencyUpdate}
     * @memberof FindjobnuServiceDTOsRequestsSkillUpdate
     */
    proficiency: FindjobnuServiceDTOsRequestsSkillProficiencyUpdate;
}



/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsSkillUpdate interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsSkillUpdate(value: object): value is FindjobnuServiceDTOsRequestsSkillUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('proficiency' in value) || value['proficiency'] === undefined) return false;
    return true;
}

export function FindjobnuServiceDTOsRequestsSkillUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsSkillUpdate {
    return FindjobnuServiceDTOsRequestsSkillUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsSkillUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsSkillUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'proficiency': FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSON(json['proficiency']),
    };
}

export function FindjobnuServiceDTOsRequestsSkillUpdateToJSON(json: any): FindjobnuServiceDTOsRequestsSkillUpdate {
    return FindjobnuServiceDTOsRequestsSkillUpdateToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsSkillUpdateToJSONTyped(value?: FindjobnuServiceDTOsRequestsSkillUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'proficiency': FindjobnuServiceDTOsRequestsSkillProficiencyUpdateToJSON(value['proficiency']),
    };
}

