/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsJobIndexPosts } from './FindjobnuServiceModelsJobIndexPosts';
import {
    FindjobnuServiceModelsJobIndexPostsFromJSON,
    FindjobnuServiceModelsJobIndexPostsFromJSONTyped,
    FindjobnuServiceModelsJobIndexPostsToJSON,
    FindjobnuServiceModelsJobIndexPostsToJSONTyped,
} from './FindjobnuServiceModelsJobIndexPosts';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts
 */
export interface FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsJobIndexPosts>}
     * @memberof FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts
     */
    items?: Array<FindjobnuServiceModelsJobIndexPosts> | null;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts interface.
 */
export function instanceOfFindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts(value: object): value is FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts {
    return true;
}

export function FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsFromJSON(json: any): FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts {
    return FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FindjobnuServiceModelsJobIndexPostsFromJSON)),
    };
}

export function FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsToJSON(json: any): FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts {
    return FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsToJSONTyped(json, false);
}

export function FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPostsToJSONTyped(value?: FindjobnuServiceModelsPagedListOfFindjobnuServiceModelsJobIndexPosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FindjobnuServiceModelsJobIndexPostsToJSON)),
    };
}

