/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsContact
 */
export interface FindjobnuServiceModelsContact {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsContact
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsContact
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsContact
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsContact
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsContact
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsContact
     */
    profile?: FindjobnuServiceModelsProfile;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsContact interface.
 */
export function instanceOfFindjobnuServiceModelsContact(value: object): value is FindjobnuServiceModelsContact {
    return true;
}

export function FindjobnuServiceModelsContactFromJSON(json: any): FindjobnuServiceModelsContact {
    return FindjobnuServiceModelsContactFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsContact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'url': json['url'] == null ? undefined : json['url'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
    };
}

export function FindjobnuServiceModelsContactToJSON(json: any): FindjobnuServiceModelsContact {
    return FindjobnuServiceModelsContactToJSONTyped(json, false);
}

export function FindjobnuServiceModelsContactToJSONTyped(value?: FindjobnuServiceModelsContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'occupation': value['occupation'],
        'url': value['url'],
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
    };
}

