/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';
import type { FindjobnuServiceModelsSkillProficiency } from './FindjobnuServiceModelsSkillProficiency';
import {
    FindjobnuServiceModelsSkillProficiencyFromJSON,
    FindjobnuServiceModelsSkillProficiencyFromJSONTyped,
    FindjobnuServiceModelsSkillProficiencyToJSON,
    FindjobnuServiceModelsSkillProficiencyToJSONTyped,
} from './FindjobnuServiceModelsSkillProficiency';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsSkill
 */
export interface FindjobnuServiceModelsSkill {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsSkill
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsSkill
     */
    name: string;
    /**
     * 
     * @type {FindjobnuServiceModelsSkillProficiency}
     * @memberof FindjobnuServiceModelsSkill
     */
    proficiency: FindjobnuServiceModelsSkillProficiency;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsSkill
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsSkill
     */
    profile?: FindjobnuServiceModelsProfile;
}



/**
 * Check if a given object implements the FindjobnuServiceModelsSkill interface.
 */
export function instanceOfFindjobnuServiceModelsSkill(value: object): value is FindjobnuServiceModelsSkill {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('proficiency' in value) || value['proficiency'] === undefined) return false;
    return true;
}

export function FindjobnuServiceModelsSkillFromJSON(json: any): FindjobnuServiceModelsSkill {
    return FindjobnuServiceModelsSkillFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'proficiency': FindjobnuServiceModelsSkillProficiencyFromJSON(json['proficiency']),
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
    };
}

export function FindjobnuServiceModelsSkillToJSON(json: any): FindjobnuServiceModelsSkill {
    return FindjobnuServiceModelsSkillToJSONTyped(json, false);
}

export function FindjobnuServiceModelsSkillToJSONTyped(value?: FindjobnuServiceModelsSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'proficiency': FindjobnuServiceModelsSkillProficiencyToJSON(value['proficiency']),
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
    };
}

