/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsEducation
 */
export interface FindjobnuServiceModelsEducation {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsEducation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    institution?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    degree?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsEducation
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsEducation
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsEducation
     */
    profile?: FindjobnuServiceModelsProfile;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsEducation interface.
 */
export function instanceOfFindjobnuServiceModelsEducation(value: object): value is FindjobnuServiceModelsEducation {
    return true;
}

export function FindjobnuServiceModelsEducationFromJSON(json: any): FindjobnuServiceModelsEducation {
    return FindjobnuServiceModelsEducationFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsEducationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsEducation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
    };
}

export function FindjobnuServiceModelsEducationToJSON(json: any): FindjobnuServiceModelsEducation {
    return FindjobnuServiceModelsEducationToJSONTyped(json, false);
}

export function FindjobnuServiceModelsEducationToJSONTyped(value?: FindjobnuServiceModelsEducation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'institution': value['institution'],
        'degree': value['degree'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
    };
}

