/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsContactUpdate
 */
export interface FindjobnuServiceDTOsRequestsContactUpdate {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsContactUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsContactUpdate
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsContactUpdate
     */
    url?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsContactUpdate interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsContactUpdate(value: object): value is FindjobnuServiceDTOsRequestsContactUpdate {
    return true;
}

export function FindjobnuServiceDTOsRequestsContactUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsContactUpdate {
    return FindjobnuServiceDTOsRequestsContactUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsContactUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsContactUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function FindjobnuServiceDTOsRequestsContactUpdateToJSON(json: any): FindjobnuServiceDTOsRequestsContactUpdate {
    return FindjobnuServiceDTOsRequestsContactUpdateToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsContactUpdateToJSONTyped(value?: FindjobnuServiceDTOsRequestsContactUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'occupation': value['occupation'],
        'url': value['url'],
    };
}

