/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsEducationDto
 */
export interface FindjobnuServiceDTOsEducationDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    institution?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    degree?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsEducationDto
     */
    linkedinUrl?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsEducationDto interface.
 */
export function instanceOfFindjobnuServiceDTOsEducationDto(value: object): value is FindjobnuServiceDTOsEducationDto {
    return true;
}

export function FindjobnuServiceDTOsEducationDtoFromJSON(json: any): FindjobnuServiceDTOsEducationDto {
    return FindjobnuServiceDTOsEducationDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsEducationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsEducationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'degree': json['degree'] == null ? undefined : json['degree'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function FindjobnuServiceDTOsEducationDtoToJSON(json: any): FindjobnuServiceDTOsEducationDto {
    return FindjobnuServiceDTOsEducationDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsEducationDtoToJSONTyped(value?: FindjobnuServiceDTOsEducationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'institution': value['institution'],
        'degree': value['degree'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

