/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsCategory } from './FindjobnuServiceModelsCategory';
import {
    FindjobnuServiceModelsCategoryFromJSON,
    FindjobnuServiceModelsCategoryFromJSONTyped,
    FindjobnuServiceModelsCategoryToJSON,
    FindjobnuServiceModelsCategoryToJSONTyped,
} from './FindjobnuServiceModelsCategory';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsJobIndexPosts
 */
export interface FindjobnuServiceModelsJobIndexPosts {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    jobID?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    companyURL?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    jobDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    jobLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    jobUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    published?: Date | null;
    /**
     * 
     * @type {Array<FindjobnuServiceModelsCategory>}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    categories?: Array<FindjobnuServiceModelsCategory> | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    bannerPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    footerPicture?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceModelsJobIndexPosts
     */
    keywords?: Array<string> | null;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsJobIndexPosts interface.
 */
export function instanceOfFindjobnuServiceModelsJobIndexPosts(value: object): value is FindjobnuServiceModelsJobIndexPosts {
    return true;
}

export function FindjobnuServiceModelsJobIndexPostsFromJSON(json: any): FindjobnuServiceModelsJobIndexPosts {
    return FindjobnuServiceModelsJobIndexPostsFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsJobIndexPostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsJobIndexPosts {
    if (json == null) {
        return json;
    }
    return {
        
        'jobID': json['jobID'] == null ? undefined : json['jobID'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'companyURL': json['companyURL'] == null ? undefined : json['companyURL'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'jobDescription': json['jobDescription'] == null ? undefined : json['jobDescription'],
        'jobLocation': json['jobLocation'] == null ? undefined : json['jobLocation'],
        'jobUrl': json['jobUrl'] == null ? undefined : json['jobUrl'],
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(FindjobnuServiceModelsCategoryFromJSON)),
        'bannerPicture': json['bannerPicture'] == null ? undefined : json['bannerPicture'],
        'footerPicture': json['footerPicture'] == null ? undefined : json['footerPicture'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function FindjobnuServiceModelsJobIndexPostsToJSON(json: any): FindjobnuServiceModelsJobIndexPosts {
    return FindjobnuServiceModelsJobIndexPostsToJSONTyped(json, false);
}

export function FindjobnuServiceModelsJobIndexPostsToJSONTyped(value?: FindjobnuServiceModelsJobIndexPosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobID': value['jobID'],
        'companyName': value['companyName'],
        'companyURL': value['companyURL'],
        'jobTitle': value['jobTitle'],
        'jobDescription': value['jobDescription'],
        'jobLocation': value['jobLocation'],
        'jobUrl': value['jobUrl'],
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(FindjobnuServiceModelsCategoryToJSON)),
        'bannerPicture': value['bannerPicture'],
        'footerPicture': value['footerPicture'],
        'keywords': value['keywords'],
    };
}

