/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsJobAgentFrequency } from './FindjobnuServiceModelsJobAgentFrequency';
import {
    FindjobnuServiceModelsJobAgentFrequencyFromJSON,
    FindjobnuServiceModelsJobAgentFrequencyFromJSONTyped,
    FindjobnuServiceModelsJobAgentFrequencyToJSON,
    FindjobnuServiceModelsJobAgentFrequencyToJSONTyped,
} from './FindjobnuServiceModelsJobAgentFrequency';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsJobAgentUpdateRequest
 */
export interface FindjobnuServiceDTOsRequestsJobAgentUpdateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsRequestsJobAgentUpdateRequest
     */
    enabled: boolean;
    /**
     * 
     * @type {FindjobnuServiceModelsJobAgentFrequency}
     * @memberof FindjobnuServiceDTOsRequestsJobAgentUpdateRequest
     */
    frequency?: FindjobnuServiceModelsJobAgentFrequency;
}



/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsJobAgentUpdateRequest interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsJobAgentUpdateRequest(value: object): value is FindjobnuServiceDTOsRequestsJobAgentUpdateRequest {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function FindjobnuServiceDTOsRequestsJobAgentUpdateRequestFromJSON(json: any): FindjobnuServiceDTOsRequestsJobAgentUpdateRequest {
    return FindjobnuServiceDTOsRequestsJobAgentUpdateRequestFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsJobAgentUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsJobAgentUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'frequency': json['frequency'] == null ? undefined : FindjobnuServiceModelsJobAgentFrequencyFromJSON(json['frequency']),
    };
}

export function FindjobnuServiceDTOsRequestsJobAgentUpdateRequestToJSON(json: any): FindjobnuServiceDTOsRequestsJobAgentUpdateRequest {
    return FindjobnuServiceDTOsRequestsJobAgentUpdateRequestToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsJobAgentUpdateRequestToJSONTyped(value?: FindjobnuServiceDTOsRequestsJobAgentUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'frequency': FindjobnuServiceModelsJobAgentFrequencyToJSON(value['frequency']),
    };
}

