/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsExperience
 */
export interface FindjobnuServiceModelsExperience {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsExperience
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    positionTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    fromDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    toDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsExperience
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsExperience
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsExperience
     */
    profile?: FindjobnuServiceModelsProfile;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsExperience interface.
 */
export function instanceOfFindjobnuServiceModelsExperience(value: object): value is FindjobnuServiceModelsExperience {
    return true;
}

export function FindjobnuServiceModelsExperienceFromJSON(json: any): FindjobnuServiceModelsExperience {
    return FindjobnuServiceModelsExperienceFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsExperienceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsExperience {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'positionTitle': json['positionTitle'] == null ? undefined : json['positionTitle'],
        'company': json['company'] == null ? undefined : json['company'],
        'fromDate': json['fromDate'] == null ? undefined : json['fromDate'],
        'toDate': json['toDate'] == null ? undefined : json['toDate'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'location': json['location'] == null ? undefined : json['location'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
    };
}

export function FindjobnuServiceModelsExperienceToJSON(json: any): FindjobnuServiceModelsExperience {
    return FindjobnuServiceModelsExperienceToJSONTyped(json, false);
}

export function FindjobnuServiceModelsExperienceToJSONTyped(value?: FindjobnuServiceModelsExperience | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'positionTitle': value['positionTitle'],
        'company': value['company'],
        'fromDate': value['fromDate'],
        'toDate': value['toDate'],
        'duration': value['duration'],
        'location': value['location'],
        'description': value['description'],
        'linkedinUrl': value['linkedinUrl'],
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
    };
}

