/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceDTOsContactDto } from './FindjobnuServiceDTOsContactDto';
import {
    FindjobnuServiceDTOsContactDtoFromJSON,
    FindjobnuServiceDTOsContactDtoFromJSONTyped,
    FindjobnuServiceDTOsContactDtoToJSON,
    FindjobnuServiceDTOsContactDtoToJSONTyped,
} from './FindjobnuServiceDTOsContactDto';
import type { FindjobnuServiceDTOsJobAgentDto } from './FindjobnuServiceDTOsJobAgentDto';
import {
    FindjobnuServiceDTOsJobAgentDtoFromJSON,
    FindjobnuServiceDTOsJobAgentDtoFromJSONTyped,
    FindjobnuServiceDTOsJobAgentDtoToJSON,
    FindjobnuServiceDTOsJobAgentDtoToJSONTyped,
} from './FindjobnuServiceDTOsJobAgentDto';
import type { FindjobnuServiceDTOsBasicInfoDto } from './FindjobnuServiceDTOsBasicInfoDto';
import {
    FindjobnuServiceDTOsBasicInfoDtoFromJSON,
    FindjobnuServiceDTOsBasicInfoDtoFromJSONTyped,
    FindjobnuServiceDTOsBasicInfoDtoToJSON,
    FindjobnuServiceDTOsBasicInfoDtoToJSONTyped,
} from './FindjobnuServiceDTOsBasicInfoDto';
import type { FindjobnuServiceDTOsExperienceDto } from './FindjobnuServiceDTOsExperienceDto';
import {
    FindjobnuServiceDTOsExperienceDtoFromJSON,
    FindjobnuServiceDTOsExperienceDtoFromJSONTyped,
    FindjobnuServiceDTOsExperienceDtoToJSON,
    FindjobnuServiceDTOsExperienceDtoToJSONTyped,
} from './FindjobnuServiceDTOsExperienceDto';
import type { FindjobnuServiceDTOsEducationDto } from './FindjobnuServiceDTOsEducationDto';
import {
    FindjobnuServiceDTOsEducationDtoFromJSON,
    FindjobnuServiceDTOsEducationDtoFromJSONTyped,
    FindjobnuServiceDTOsEducationDtoToJSON,
    FindjobnuServiceDTOsEducationDtoToJSONTyped,
} from './FindjobnuServiceDTOsEducationDto';
import type { FindjobnuServiceDTOsSkillDto } from './FindjobnuServiceDTOsSkillDto';
import {
    FindjobnuServiceDTOsSkillDtoFromJSON,
    FindjobnuServiceDTOsSkillDtoFromJSONTyped,
    FindjobnuServiceDTOsSkillDtoToJSON,
    FindjobnuServiceDTOsSkillDtoToJSONTyped,
} from './FindjobnuServiceDTOsSkillDto';
import type { FindjobnuServiceDTOsAccomplishmentDto } from './FindjobnuServiceDTOsAccomplishmentDto';
import {
    FindjobnuServiceDTOsAccomplishmentDtoFromJSON,
    FindjobnuServiceDTOsAccomplishmentDtoFromJSONTyped,
    FindjobnuServiceDTOsAccomplishmentDtoToJSON,
    FindjobnuServiceDTOsAccomplishmentDtoToJSONTyped,
} from './FindjobnuServiceDTOsAccomplishmentDto';
import type { FindjobnuServiceDTOsInterestDto } from './FindjobnuServiceDTOsInterestDto';
import {
    FindjobnuServiceDTOsInterestDtoFromJSON,
    FindjobnuServiceDTOsInterestDtoFromJSONTyped,
    FindjobnuServiceDTOsInterestDtoToJSON,
    FindjobnuServiceDTOsInterestDtoToJSONTyped,
} from './FindjobnuServiceDTOsInterestDto';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsProfileDto
 */
export interface FindjobnuServiceDTOsProfileDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    userId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    lastUpdatedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    savedJobPosts?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    keywords?: Array<string> | null;
    /**
     * 
     * @type {FindjobnuServiceDTOsBasicInfoDto}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    basicInfo?: FindjobnuServiceDTOsBasicInfoDto;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsExperienceDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    experiences?: Array<FindjobnuServiceDTOsExperienceDto> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsEducationDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    educations?: Array<FindjobnuServiceDTOsEducationDto> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsInterestDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    interests?: Array<FindjobnuServiceDTOsInterestDto> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsAccomplishmentDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    accomplishments?: Array<FindjobnuServiceDTOsAccomplishmentDto> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsContactDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    contacts?: Array<FindjobnuServiceDTOsContactDto> | null;
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsSkillDto>}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    skills?: Array<FindjobnuServiceDTOsSkillDto> | null;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    hasJobAgent?: boolean;
    /**
     * 
     * @type {FindjobnuServiceDTOsJobAgentDto}
     * @memberof FindjobnuServiceDTOsProfileDto
     */
    jobAgent?: FindjobnuServiceDTOsJobAgentDto;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsProfileDto interface.
 */
export function instanceOfFindjobnuServiceDTOsProfileDto(value: object): value is FindjobnuServiceDTOsProfileDto {
    return true;
}

export function FindjobnuServiceDTOsProfileDtoFromJSON(json: any): FindjobnuServiceDTOsProfileDto {
    return FindjobnuServiceDTOsProfileDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'lastUpdatedAt': json['lastUpdatedAt'] == null ? undefined : (new Date(json['lastUpdatedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'savedJobPosts': json['savedJobPosts'] == null ? undefined : json['savedJobPosts'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'basicInfo': json['basicInfo'] == null ? undefined : FindjobnuServiceDTOsBasicInfoDtoFromJSON(json['basicInfo']),
        'experiences': json['experiences'] == null ? undefined : ((json['experiences'] as Array<any>).map(FindjobnuServiceDTOsExperienceDtoFromJSON)),
        'educations': json['educations'] == null ? undefined : ((json['educations'] as Array<any>).map(FindjobnuServiceDTOsEducationDtoFromJSON)),
        'interests': json['interests'] == null ? undefined : ((json['interests'] as Array<any>).map(FindjobnuServiceDTOsInterestDtoFromJSON)),
        'accomplishments': json['accomplishments'] == null ? undefined : ((json['accomplishments'] as Array<any>).map(FindjobnuServiceDTOsAccomplishmentDtoFromJSON)),
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(FindjobnuServiceDTOsContactDtoFromJSON)),
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(FindjobnuServiceDTOsSkillDtoFromJSON)),
        'hasJobAgent': json['hasJobAgent'] == null ? undefined : json['hasJobAgent'],
        'jobAgent': json['jobAgent'] == null ? undefined : FindjobnuServiceDTOsJobAgentDtoFromJSON(json['jobAgent']),
    };
}

export function FindjobnuServiceDTOsProfileDtoToJSON(json: any): FindjobnuServiceDTOsProfileDto {
    return FindjobnuServiceDTOsProfileDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsProfileDtoToJSONTyped(value?: FindjobnuServiceDTOsProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'lastUpdatedAt': value['lastUpdatedAt'] == null ? undefined : ((value['lastUpdatedAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'savedJobPosts': value['savedJobPosts'],
        'keywords': value['keywords'],
        'basicInfo': FindjobnuServiceDTOsBasicInfoDtoToJSON(value['basicInfo']),
        'experiences': value['experiences'] == null ? undefined : ((value['experiences'] as Array<any>).map(FindjobnuServiceDTOsExperienceDtoToJSON)),
        'educations': value['educations'] == null ? undefined : ((value['educations'] as Array<any>).map(FindjobnuServiceDTOsEducationDtoToJSON)),
        'interests': value['interests'] == null ? undefined : ((value['interests'] as Array<any>).map(FindjobnuServiceDTOsInterestDtoToJSON)),
        'accomplishments': value['accomplishments'] == null ? undefined : ((value['accomplishments'] as Array<any>).map(FindjobnuServiceDTOsAccomplishmentDtoToJSON)),
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(FindjobnuServiceDTOsContactDtoToJSON)),
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(FindjobnuServiceDTOsSkillDtoToJSON)),
        'hasJobAgent': value['hasJobAgent'],
        'jobAgent': FindjobnuServiceDTOsJobAgentDtoToJSON(value['jobAgent']),
    };
}

