/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FindjobnuServiceDTOsRequestsSkillProficiencyUpdate = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type FindjobnuServiceDTOsRequestsSkillProficiencyUpdate = typeof FindjobnuServiceDTOsRequestsSkillProficiencyUpdate[keyof typeof FindjobnuServiceDTOsRequestsSkillProficiencyUpdate];


export function instanceOfFindjobnuServiceDTOsRequestsSkillProficiencyUpdate(value: any): boolean {
    for (const key in FindjobnuServiceDTOsRequestsSkillProficiencyUpdate) {
        if (Object.prototype.hasOwnProperty.call(FindjobnuServiceDTOsRequestsSkillProficiencyUpdate, key)) {
            if (FindjobnuServiceDTOsRequestsSkillProficiencyUpdate[key as keyof typeof FindjobnuServiceDTOsRequestsSkillProficiencyUpdate] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsSkillProficiencyUpdate {
    return FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsSkillProficiencyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsSkillProficiencyUpdate {
    return json as FindjobnuServiceDTOsRequestsSkillProficiencyUpdate;
}

export function FindjobnuServiceDTOsRequestsSkillProficiencyUpdateToJSON(value?: FindjobnuServiceDTOsRequestsSkillProficiencyUpdate | null): any {
    return value as any;
}

export function FindjobnuServiceDTOsRequestsSkillProficiencyUpdateToJSONTyped(value: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsSkillProficiencyUpdate {
    return value as FindjobnuServiceDTOsRequestsSkillProficiencyUpdate;
}

