/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsBasicInfoDto
 */
export interface FindjobnuServiceDTOsBasicInfoDto {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    lastName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    about?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsBasicInfoDto
     */
    openToWork?: boolean;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsBasicInfoDto interface.
 */
export function instanceOfFindjobnuServiceDTOsBasicInfoDto(value: object): value is FindjobnuServiceDTOsBasicInfoDto {
    return true;
}

export function FindjobnuServiceDTOsBasicInfoDtoFromJSON(json: any): FindjobnuServiceDTOsBasicInfoDto {
    return FindjobnuServiceDTOsBasicInfoDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsBasicInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsBasicInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'about': json['about'] == null ? undefined : json['about'],
        'location': json['location'] == null ? undefined : json['location'],
        'company': json['company'] == null ? undefined : json['company'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'openToWork': json['openToWork'] == null ? undefined : json['openToWork'],
    };
}

export function FindjobnuServiceDTOsBasicInfoDtoToJSON(json: any): FindjobnuServiceDTOsBasicInfoDto {
    return FindjobnuServiceDTOsBasicInfoDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsBasicInfoDtoToJSONTyped(value?: FindjobnuServiceDTOsBasicInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'dateOfBirth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth'] as any).toISOString()),
        'phoneNumber': value['phoneNumber'],
        'about': value['about'],
        'location': value['location'],
        'company': value['company'],
        'jobTitle': value['jobTitle'],
        'linkedinUrl': value['linkedinUrl'],
        'openToWork': value['openToWork'],
    };
}

