/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceDTOsResponsesJobIndexPostResponse } from './FindjobnuServiceDTOsResponsesJobIndexPostResponse';
import {
    FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON,
    FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped,
} from './FindjobnuServiceDTOsResponsesJobIndexPostResponse';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse
 */
export interface FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse {
    /**
     * 
     * @type {Array<FindjobnuServiceDTOsResponsesJobIndexPostResponse>}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    items?: Array<FindjobnuServiceDTOsResponsesJobIndexPostResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse interface.
 */
export function instanceOfFindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse(value: object): value is FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return true;
}

export function FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON(json: any): FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON(json: any): FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped(value?: FindjobnuServiceDTOsResponsesPagedResponseOfFindjobnuServiceDTOsResponsesJobIndexPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
    };
}

