/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsProfileUpdateRequest
 */
export interface FindjobnuServiceDTOsRequestsProfileUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileUpdateRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileUpdateRequest
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileUpdateRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileUpdateRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsProfileUpdateRequest
     */
    summary?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsProfileUpdateRequest interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsProfileUpdateRequest(value: object): value is FindjobnuServiceDTOsRequestsProfileUpdateRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function FindjobnuServiceDTOsRequestsProfileUpdateRequestFromJSON(json: any): FindjobnuServiceDTOsRequestsProfileUpdateRequest {
    return FindjobnuServiceDTOsRequestsProfileUpdateRequestFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsProfileUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsProfileUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function FindjobnuServiceDTOsRequestsProfileUpdateRequestToJSON(json: any): FindjobnuServiceDTOsRequestsProfileUpdateRequest {
    return FindjobnuServiceDTOsRequestsProfileUpdateRequestToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsProfileUpdateRequestToJSONTyped(value?: FindjobnuServiceDTOsRequestsProfileUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'fullName': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'summary': value['summary'],
    };
}

