/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsJobAgentDto
 */
export interface FindjobnuServiceDTOsJobAgentDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    frequency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    lastSentAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    nextSendAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsJobAgentDto
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsJobAgentDto interface.
 */
export function instanceOfFindjobnuServiceDTOsJobAgentDto(value: object): value is FindjobnuServiceDTOsJobAgentDto {
    return true;
}

export function FindjobnuServiceDTOsJobAgentDtoFromJSON(json: any): FindjobnuServiceDTOsJobAgentDto {
    return FindjobnuServiceDTOsJobAgentDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsJobAgentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsJobAgentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'lastSentAt': json['lastSentAt'] == null ? undefined : (new Date(json['lastSentAt'])),
        'nextSendAt': json['nextSendAt'] == null ? undefined : (new Date(json['nextSendAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function FindjobnuServiceDTOsJobAgentDtoToJSON(json: any): FindjobnuServiceDTOsJobAgentDto {
    return FindjobnuServiceDTOsJobAgentDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsJobAgentDtoToJSONTyped(value?: FindjobnuServiceDTOsJobAgentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'enabled': value['enabled'],
        'frequency': value['frequency'],
        'lastSentAt': value['lastSentAt'] == null ? undefined : ((value['lastSentAt'] as any).toISOString()),
        'nextSendAt': value['nextSendAt'] == null ? undefined : ((value['nextSendAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

