/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsInterestDto
 */
export interface FindjobnuServiceDTOsInterestDto {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsInterestDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsInterestDto
     */
    title?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsInterestDto interface.
 */
export function instanceOfFindjobnuServiceDTOsInterestDto(value: object): value is FindjobnuServiceDTOsInterestDto {
    return true;
}

export function FindjobnuServiceDTOsInterestDtoFromJSON(json: any): FindjobnuServiceDTOsInterestDto {
    return FindjobnuServiceDTOsInterestDtoFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsInterestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsInterestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function FindjobnuServiceDTOsInterestDtoToJSON(json: any): FindjobnuServiceDTOsInterestDto {
    return FindjobnuServiceDTOsInterestDtoToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsInterestDtoToJSONTyped(value?: FindjobnuServiceDTOsInterestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

