/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceModelsProfile } from './FindjobnuServiceModelsProfile';
import {
    FindjobnuServiceModelsProfileFromJSON,
    FindjobnuServiceModelsProfileFromJSONTyped,
    FindjobnuServiceModelsProfileToJSON,
    FindjobnuServiceModelsProfileToJSONTyped,
} from './FindjobnuServiceModelsProfile';

/**
 * 
 * @export
 * @interface FindjobnuServiceModelsInterest
 */
export interface FindjobnuServiceModelsInterest {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsInterest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceModelsInterest
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceModelsInterest
     */
    profileId?: number;
    /**
     * 
     * @type {FindjobnuServiceModelsProfile}
     * @memberof FindjobnuServiceModelsInterest
     */
    profile?: FindjobnuServiceModelsProfile;
}

/**
 * Check if a given object implements the FindjobnuServiceModelsInterest interface.
 */
export function instanceOfFindjobnuServiceModelsInterest(value: object): value is FindjobnuServiceModelsInterest {
    return true;
}

export function FindjobnuServiceModelsInterestFromJSON(json: any): FindjobnuServiceModelsInterest {
    return FindjobnuServiceModelsInterestFromJSONTyped(json, false);
}

export function FindjobnuServiceModelsInterestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceModelsInterest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : FindjobnuServiceModelsProfileFromJSON(json['profile']),
    };
}

export function FindjobnuServiceModelsInterestToJSON(json: any): FindjobnuServiceModelsInterest {
    return FindjobnuServiceModelsInterestToJSONTyped(json, false);
}

export function FindjobnuServiceModelsInterestToJSONTyped(value?: FindjobnuServiceModelsInterest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'profileId': value['profileId'],
        'profile': FindjobnuServiceModelsProfileToJSON(value['profile']),
    };
}

