/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsResponsesJobIndexPostResponse
 */
export interface FindjobnuServiceDTOsResponsesJobIndexPostResponse {
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    jobUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    postedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    companyUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    bannerPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    footerPicture?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FindjobnuServiceDTOsResponsesJobIndexPostResponse
     */
    keywords?: Array<string> | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsResponsesJobIndexPostResponse interface.
 */
export function instanceOfFindjobnuServiceDTOsResponsesJobIndexPostResponse(value: object): value is FindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return true;
}

export function FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSON(json: any): FindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesJobIndexPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsResponsesJobIndexPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'jobUrl': json['jobUrl'] == null ? undefined : json['jobUrl'],
        'postedDate': json['postedDate'] == null ? undefined : (new Date(json['postedDate'])),
        'category': json['category'] == null ? undefined : json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'companyUrl': json['companyUrl'] == null ? undefined : json['companyUrl'],
        'bannerPicture': json['bannerPicture'] == null ? undefined : json['bannerPicture'],
        'footerPicture': json['footerPicture'] == null ? undefined : json['footerPicture'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSON(json: any): FindjobnuServiceDTOsResponsesJobIndexPostResponse {
    return FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsResponsesJobIndexPostResponseToJSONTyped(value?: FindjobnuServiceDTOsResponsesJobIndexPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'location': value['location'],
        'jobUrl': value['jobUrl'],
        'postedDate': value['postedDate'] == null ? undefined : ((value['postedDate']).toISOString()),
        'category': value['category'],
        'description': value['description'],
        'companyUrl': value['companyUrl'],
        'bannerPicture': value['bannerPicture'],
        'footerPicture': value['footerPicture'],
        'keywords': value['keywords'],
    };
}

