/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsAccomplishmentUpdate
 */
export interface FindjobnuServiceDTOsRequestsAccomplishmentUpdate {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsAccomplishmentUpdate
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsAccomplishmentUpdate
     */
    title?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsAccomplishmentUpdate interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsAccomplishmentUpdate(value: object): value is FindjobnuServiceDTOsRequestsAccomplishmentUpdate {
    return true;
}

export function FindjobnuServiceDTOsRequestsAccomplishmentUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsAccomplishmentUpdate {
    return FindjobnuServiceDTOsRequestsAccomplishmentUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsAccomplishmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsAccomplishmentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function FindjobnuServiceDTOsRequestsAccomplishmentUpdateToJSON(json: any): FindjobnuServiceDTOsRequestsAccomplishmentUpdate {
    return FindjobnuServiceDTOsRequestsAccomplishmentUpdateToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsAccomplishmentUpdateToJSONTyped(value?: FindjobnuServiceDTOsRequestsAccomplishmentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'title': value['title'],
    };
}

