/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsRequestsInterestUpdate
 */
export interface FindjobnuServiceDTOsRequestsInterestUpdate {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsRequestsInterestUpdate
     */
    title?: string | null;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsRequestsInterestUpdate interface.
 */
export function instanceOfFindjobnuServiceDTOsRequestsInterestUpdate(value: object): value is FindjobnuServiceDTOsRequestsInterestUpdate {
    return true;
}

export function FindjobnuServiceDTOsRequestsInterestUpdateFromJSON(json: any): FindjobnuServiceDTOsRequestsInterestUpdate {
    return FindjobnuServiceDTOsRequestsInterestUpdateFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsInterestUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsRequestsInterestUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function FindjobnuServiceDTOsRequestsInterestUpdateToJSON(json: any): FindjobnuServiceDTOsRequestsInterestUpdate {
    return FindjobnuServiceDTOsRequestsInterestUpdateToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsRequestsInterestUpdateToJSONTyped(value?: FindjobnuServiceDTOsRequestsInterestUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

