/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService API
 * API documentation for FindjobnuService
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FindjobnuServiceDTOsCvReadabilitySummary } from './FindjobnuServiceDTOsCvReadabilitySummary';
import {
    FindjobnuServiceDTOsCvReadabilitySummaryFromJSON,
    FindjobnuServiceDTOsCvReadabilitySummaryFromJSONTyped,
    FindjobnuServiceDTOsCvReadabilitySummaryToJSON,
    FindjobnuServiceDTOsCvReadabilitySummaryToJSONTyped,
} from './FindjobnuServiceDTOsCvReadabilitySummary';

/**
 * 
 * @export
 * @interface FindjobnuServiceDTOsCvReadabilityResult
 */
export interface FindjobnuServiceDTOsCvReadabilityResult {
    /**
     * 
     * @type {string}
     * @memberof FindjobnuServiceDTOsCvReadabilityResult
     */
    extractedText?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FindjobnuServiceDTOsCvReadabilityResult
     */
    readabilityScore?: number;
    /**
     * 
     * @type {FindjobnuServiceDTOsCvReadabilitySummary}
     * @memberof FindjobnuServiceDTOsCvReadabilityResult
     */
    summary?: FindjobnuServiceDTOsCvReadabilitySummary;
}

/**
 * Check if a given object implements the FindjobnuServiceDTOsCvReadabilityResult interface.
 */
export function instanceOfFindjobnuServiceDTOsCvReadabilityResult(value: object): value is FindjobnuServiceDTOsCvReadabilityResult {
    return true;
}

export function FindjobnuServiceDTOsCvReadabilityResultFromJSON(json: any): FindjobnuServiceDTOsCvReadabilityResult {
    return FindjobnuServiceDTOsCvReadabilityResultFromJSONTyped(json, false);
}

export function FindjobnuServiceDTOsCvReadabilityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindjobnuServiceDTOsCvReadabilityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'extractedText': json['extractedText'] == null ? undefined : json['extractedText'],
        'readabilityScore': json['readabilityScore'] == null ? undefined : json['readabilityScore'],
        'summary': json['summary'] == null ? undefined : FindjobnuServiceDTOsCvReadabilitySummaryFromJSON(json['summary']),
    };
}

export function FindjobnuServiceDTOsCvReadabilityResultToJSON(json: any): FindjobnuServiceDTOsCvReadabilityResult {
    return FindjobnuServiceDTOsCvReadabilityResultToJSONTyped(json, false);
}

export function FindjobnuServiceDTOsCvReadabilityResultToJSONTyped(value?: FindjobnuServiceDTOsCvReadabilityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extractedText': value['extractedText'],
        'readabilityScore': value['readabilityScore'],
        'summary': FindjobnuServiceDTOsCvReadabilitySummaryToJSON(value['summary']),
    };
}

