/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterestUpdate
 */
export interface InterestUpdate {
    /**
     * 
     * @type {string}
     * @memberof InterestUpdate
     */
    title?: string | null;
}

/**
 * Check if a given object implements the InterestUpdate interface.
 */
export function instanceOfInterestUpdate(value: object): value is InterestUpdate {
    return true;
}

export function InterestUpdateFromJSON(json: any): InterestUpdate {
    return InterestUpdateFromJSONTyped(json, false);
}

export function InterestUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function InterestUpdateToJSON(json: any): InterestUpdate {
    return InterestUpdateToJSONTyped(json, false);
}

export function InterestUpdateToJSONTyped(value?: InterestUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

