/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterestDto
 */
export interface InterestDto {
    /**
     * 
     * @type {number}
     * @memberof InterestDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InterestDto
     */
    title?: string | null;
}

/**
 * Check if a given object implements the InterestDto interface.
 */
export function instanceOfInterestDto(value: object): value is InterestDto {
    return true;
}

export function InterestDtoFromJSON(json: any): InterestDto {
    return InterestDtoFromJSONTyped(json, false);
}

export function InterestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function InterestDtoToJSON(json: any): InterestDto {
    return InterestDtoToJSONTyped(json, false);
}

export function InterestDtoToJSONTyped(value?: InterestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

