/* tslint:disable */
/* eslint-disable */
/**
 * findjobnuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Profile } from './Profile';
import {
    ProfileFromJSON,
    ProfileFromJSONTyped,
    ProfileToJSON,
    ProfileToJSONTyped,
} from './Profile';

/**
 * 
 * @export
 * @interface Interest
 */
export interface Interest {
    /**
     * 
     * @type {number}
     * @memberof Interest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Interest
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Interest
     */
    profileId?: number;
    /**
     * 
     * @type {Profile}
     * @memberof Interest
     */
    profile?: Profile;
}

/**
 * Check if a given object implements the Interest interface.
 */
export function instanceOfInterest(value: object): value is Interest {
    return true;
}

export function InterestFromJSON(json: any): Interest {
    return InterestFromJSONTyped(json, false);
}

export function InterestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Interest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'profileId': json['profileId'] == null ? undefined : json['profileId'],
        'profile': json['profile'] == null ? undefined : ProfileFromJSON(json['profile']),
    };
}

export function InterestToJSON(json: any): Interest {
    return InterestToJSONTyped(json, false);
}

export function InterestToJSONTyped(value?: Interest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'profileId': value['profileId'],
        'profile': ProfileToJSON(value['profile']),
    };
}

