/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobAgentDto
 */
export interface JobAgentDto {
    /**
     * 
     * @type {number}
     * @memberof JobAgentDto
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JobAgentDto
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JobAgentDto
     */
    frequency?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobAgentDto
     */
    lastSentAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JobAgentDto
     */
    nextSendAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof JobAgentDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobAgentDto
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the JobAgentDto interface.
 */
export function instanceOfJobAgentDto(value: object): value is JobAgentDto {
    return true;
}

export function JobAgentDtoFromJSON(json: any): JobAgentDto {
    return JobAgentDtoFromJSONTyped(json, false);
}

export function JobAgentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobAgentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'lastSentAt': json['lastSentAt'] == null ? undefined : (new Date(json['lastSentAt'])),
        'nextSendAt': json['nextSendAt'] == null ? undefined : (new Date(json['nextSendAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function JobAgentDtoToJSON(json: any): JobAgentDto {
    return JobAgentDtoToJSONTyped(json, false);
}

export function JobAgentDtoToJSONTyped(value?: JobAgentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'enabled': value['enabled'],
        'frequency': value['frequency'],
        'lastSentAt': value['lastSentAt'] == null ? undefined : ((value['lastSentAt'] as any).toISOString()),
        'nextSendAt': value['nextSendAt'] == null ? undefined : ((value['nextSendAt'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

