/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobAgentFrequency } from './JobAgentFrequency';
import {
    JobAgentFrequencyFromJSON,
    JobAgentFrequencyFromJSONTyped,
    JobAgentFrequencyToJSON,
    JobAgentFrequencyToJSONTyped,
} from './JobAgentFrequency';

/**
 * 
 * @export
 * @interface JobAgentUpdateRequest
 */
export interface JobAgentUpdateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof JobAgentUpdateRequest
     */
    enabled: boolean;
    /**
     * 
     * @type {JobAgentFrequency}
     * @memberof JobAgentUpdateRequest
     */
    frequency?: JobAgentFrequency;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobAgentUpdateRequest
     */
    preferredLocations?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof JobAgentUpdateRequest
     */
    preferredCategoryIds?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobAgentUpdateRequest
     */
    includeKeywords?: Array<string> | null;
}



/**
 * Check if a given object implements the JobAgentUpdateRequest interface.
 */
export function instanceOfJobAgentUpdateRequest(value: object): value is JobAgentUpdateRequest {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function JobAgentUpdateRequestFromJSON(json: any): JobAgentUpdateRequest {
    return JobAgentUpdateRequestFromJSONTyped(json, false);
}

export function JobAgentUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobAgentUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'frequency': json['frequency'] == null ? undefined : JobAgentFrequencyFromJSON(json['frequency']),
        'preferredLocations': json['preferredLocations'] == null ? undefined : json['preferredLocations'],
        'preferredCategoryIds': json['preferredCategoryIds'] == null ? undefined : json['preferredCategoryIds'],
        'includeKeywords': json['includeKeywords'] == null ? undefined : json['includeKeywords'],
    };
}

export function JobAgentUpdateRequestToJSON(json: any): JobAgentUpdateRequest {
    return JobAgentUpdateRequestToJSONTyped(json, false);
}

export function JobAgentUpdateRequestToJSONTyped(value?: JobAgentUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'frequency': JobAgentFrequencyToJSON(value['frequency']),
        'preferredLocations': value['preferredLocations'],
        'preferredCategoryIds': value['preferredCategoryIds'],
        'includeKeywords': value['includeKeywords'],
    };
}

