/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobIndexPostResponse } from './JobIndexPostResponse';
import {
    JobIndexPostResponseFromJSON,
    JobIndexPostResponseFromJSONTyped,
    JobIndexPostResponseToJSON,
    JobIndexPostResponseToJSONTyped,
} from './JobIndexPostResponse';

/**
 * 
 * @export
 * @interface JobIndexPostResponsePagedResponse
 */
export interface JobIndexPostResponsePagedResponse {
    /**
     * 
     * @type {Array<JobIndexPostResponse>}
     * @memberof JobIndexPostResponsePagedResponse
     */
    items?: Array<JobIndexPostResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostResponsePagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostResponsePagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostResponsePagedResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the JobIndexPostResponsePagedResponse interface.
 */
export function instanceOfJobIndexPostResponsePagedResponse(value: object): value is JobIndexPostResponsePagedResponse {
    return true;
}

export function JobIndexPostResponsePagedResponseFromJSON(json: any): JobIndexPostResponsePagedResponse {
    return JobIndexPostResponsePagedResponseFromJSONTyped(json, false);
}

export function JobIndexPostResponsePagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIndexPostResponsePagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(JobIndexPostResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function JobIndexPostResponsePagedResponseToJSON(json: any): JobIndexPostResponsePagedResponse {
    return JobIndexPostResponsePagedResponseToJSONTyped(json, false);
}

export function JobIndexPostResponsePagedResponseToJSONTyped(value?: JobIndexPostResponsePagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JobIndexPostResponseToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
    };
}

