/* tslint:disable */
/* eslint-disable */
/**
 * findjobnuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobIndexPosts } from './JobIndexPosts';
import {
    JobIndexPostsFromJSON,
    JobIndexPostsFromJSONTyped,
    JobIndexPostsToJSON,
    JobIndexPostsToJSONTyped,
} from './JobIndexPosts';

/**
 * 
 * @export
 * @interface JobIndexPostsPagedList
 */
export interface JobIndexPostsPagedList {
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostsPagedList
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostsPagedList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostsPagedList
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<JobIndexPosts>}
     * @memberof JobIndexPostsPagedList
     */
    items?: Array<JobIndexPosts> | null;
}

/**
 * Check if a given object implements the JobIndexPostsPagedList interface.
 */
export function instanceOfJobIndexPostsPagedList(value: object): value is JobIndexPostsPagedList {
    return true;
}

export function JobIndexPostsPagedListFromJSON(json: any): JobIndexPostsPagedList {
    return JobIndexPostsPagedListFromJSONTyped(json, false);
}

export function JobIndexPostsPagedListFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIndexPostsPagedList {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(JobIndexPostsFromJSON)),
    };
}

export function JobIndexPostsPagedListToJSON(json: any): JobIndexPostsPagedList {
    return JobIndexPostsPagedListToJSONTyped(json, false);
}

export function JobIndexPostsPagedListToJSONTyped(value?: JobIndexPostsPagedList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(JobIndexPostsToJSON)),
    };
}

