/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobIndexPostResponse
 */
export interface JobIndexPostResponse {
    /**
     * 
     * @type {number}
     * @memberof JobIndexPostResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    jobUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobIndexPostResponse
     */
    postedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    companyUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    bannerPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    footerPicture?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof JobIndexPostResponse
     */
    keywords?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    bannerFormat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    footerFormat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    bannerMimeType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPostResponse
     */
    footerMimeType?: string | null;
}

/**
 * Check if a given object implements the JobIndexPostResponse interface.
 */
export function instanceOfJobIndexPostResponse(value: object): value is JobIndexPostResponse {
    return true;
}

export function JobIndexPostResponseFromJSON(json: any): JobIndexPostResponse {
    return JobIndexPostResponseFromJSONTyped(json, false);
}

export function JobIndexPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIndexPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'jobUrl': json['jobUrl'] == null ? undefined : json['jobUrl'],
        'postedDate': json['postedDate'] == null ? undefined : (new Date(json['postedDate'])),
        'category': json['category'] == null ? undefined : json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'companyUrl': json['companyUrl'] == null ? undefined : json['companyUrl'],
        'bannerPicture': json['bannerPicture'] == null ? undefined : json['bannerPicture'],
        'footerPicture': json['footerPicture'] == null ? undefined : json['footerPicture'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'bannerFormat': json['bannerFormat'] == null ? undefined : json['bannerFormat'],
        'footerFormat': json['footerFormat'] == null ? undefined : json['footerFormat'],
        'bannerMimeType': json['bannerMimeType'] == null ? undefined : json['bannerMimeType'],
        'footerMimeType': json['footerMimeType'] == null ? undefined : json['footerMimeType'],
    };
}

export function JobIndexPostResponseToJSON(json: any): JobIndexPostResponse {
    return JobIndexPostResponseToJSONTyped(json, false);
}

export function JobIndexPostResponseToJSONTyped(value?: JobIndexPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'location': value['location'],
        'jobUrl': value['jobUrl'],
        'postedDate': value['postedDate'] == null ? undefined : ((value['postedDate']).toISOString()),
        'category': value['category'],
        'description': value['description'],
        'companyUrl': value['companyUrl'],
        'bannerPicture': value['bannerPicture'],
        'footerPicture': value['footerPicture'],
        'keywords': value['keywords'],
        'bannerFormat': value['bannerFormat'],
        'footerFormat': value['footerFormat'],
        'bannerMimeType': value['bannerMimeType'],
        'footerMimeType': value['footerMimeType'],
    };
}

