/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface JobIndexPosts
 */
export interface JobIndexPosts {
    /**
     * 
     * @type {number}
     * @memberof JobIndexPosts
     */
    jobID?: number;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    companyURL?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    jobDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    jobLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    jobUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof JobIndexPosts
     */
    published?: Date | null;
    /**
     * 
     * @type {Array<Category>}
     * @memberof JobIndexPosts
     */
    categories?: Array<Category> | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    bannerPicture?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobIndexPosts
     */
    footerPicture?: string | null;
}

/**
 * Check if a given object implements the JobIndexPosts interface.
 */
export function instanceOfJobIndexPosts(value: object): value is JobIndexPosts {
    return true;
}

export function JobIndexPostsFromJSON(json: any): JobIndexPosts {
    return JobIndexPostsFromJSONTyped(json, false);
}

export function JobIndexPostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIndexPosts {
    if (json == null) {
        return json;
    }
    return {
        
        'jobID': json['jobID'] == null ? undefined : json['jobID'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'companyURL': json['companyURL'] == null ? undefined : json['companyURL'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'jobDescription': json['jobDescription'] == null ? undefined : json['jobDescription'],
        'jobLocation': json['jobLocation'] == null ? undefined : json['jobLocation'],
        'jobUrl': json['jobUrl'] == null ? undefined : json['jobUrl'],
        'published': json['published'] == null ? undefined : (new Date(json['published'])),
        'categories': json['categories'] == null ? undefined : ((json['categories'] as Array<any>).map(CategoryFromJSON)),
        'bannerPicture': json['bannerPicture'] == null ? undefined : json['bannerPicture'],
        'footerPicture': json['footerPicture'] == null ? undefined : json['footerPicture'],
    };
}

export function JobIndexPostsToJSON(json: any): JobIndexPosts {
    return JobIndexPostsToJSONTyped(json, false);
}

export function JobIndexPostsToJSONTyped(value?: JobIndexPosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobID': value['jobID'],
        'companyName': value['companyName'],
        'companyURL': value['companyURL'],
        'jobTitle': value['jobTitle'],
        'jobDescription': value['jobDescription'],
        'jobLocation': value['jobLocation'],
        'jobUrl': value['jobUrl'],
        'published': value['published'] == null ? undefined : ((value['published'] as any).toISOString()),
        'categories': value['categories'] == null ? undefined : ((value['categories'] as Array<any>).map(CategoryToJSON)),
        'bannerPicture': value['bannerPicture'],
        'footerPicture': value['footerPicture'],
    };
}

