/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsletterSubscribeRequest
 */
export interface NewsletterSubscribeRequest {
    /**
     * 
     * @type {string}
     * @memberof NewsletterSubscribeRequest
     */
    email: string;
}

/**
 * Check if a given object implements the NewsletterSubscribeRequest interface.
 */
export function instanceOfNewsletterSubscribeRequest(value: object): value is NewsletterSubscribeRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function NewsletterSubscribeRequestFromJSON(json: any): NewsletterSubscribeRequest {
    return NewsletterSubscribeRequestFromJSONTyped(json, false);
}

export function NewsletterSubscribeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterSubscribeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function NewsletterSubscribeRequestToJSON(json: any): NewsletterSubscribeRequest {
    return NewsletterSubscribeRequestToJSONTyped(json, false);
}

export function NewsletterSubscribeRequestToJSONTyped(value?: NewsletterSubscribeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

