/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewsletterSubscribeResponse
 */
export interface NewsletterSubscribeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof NewsletterSubscribeResponse
     */
    success?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NewsletterSubscribeResponse
     */
    alreadySubscribed?: boolean;
}

/**
 * Check if a given object implements the NewsletterSubscribeResponse interface.
 */
export function instanceOfNewsletterSubscribeResponse(value: object): value is NewsletterSubscribeResponse {
    return true;
}

export function NewsletterSubscribeResponseFromJSON(json: any): NewsletterSubscribeResponse {
    return NewsletterSubscribeResponseFromJSONTyped(json, false);
}

export function NewsletterSubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewsletterSubscribeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'alreadySubscribed': json['alreadySubscribed'] == null ? undefined : json['alreadySubscribed'],
    };
}

export function NewsletterSubscribeResponseToJSON(json: any): NewsletterSubscribeResponse {
    return NewsletterSubscribeResponseToJSONTyped(json, false);
}

export function NewsletterSubscribeResponseToJSONTyped(value?: NewsletterSubscribeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'alreadySubscribed': value['alreadySubscribed'],
    };
}

