/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileCreateRequest
 */
export interface ProfileCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProfileCreateRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreateRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreateRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreateRequest
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileCreateRequest
     */
    summary?: string | null;
}

/**
 * Check if a given object implements the ProfileCreateRequest interface.
 */
export function instanceOfProfileCreateRequest(value: object): value is ProfileCreateRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function ProfileCreateRequestFromJSON(json: any): ProfileCreateRequest {
    return ProfileCreateRequestFromJSONTyped(json, false);
}

export function ProfileCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'fullName': json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function ProfileCreateRequestToJSON(json: any): ProfileCreateRequest {
    return ProfileCreateRequestToJSONTyped(json, false);
}

export function ProfileCreateRequestToJSONTyped(value?: ProfileCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'fullName': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'summary': value['summary'],
    };
}

