/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationUpdate } from './EducationUpdate';
import {
    EducationUpdateFromJSON,
    EducationUpdateFromJSONTyped,
    EducationUpdateToJSON,
    EducationUpdateToJSONTyped,
} from './EducationUpdate';
import type { AccomplishmentUpdate } from './AccomplishmentUpdate';
import {
    AccomplishmentUpdateFromJSON,
    AccomplishmentUpdateFromJSONTyped,
    AccomplishmentUpdateToJSON,
    AccomplishmentUpdateToJSONTyped,
} from './AccomplishmentUpdate';
import type { SkillUpdate } from './SkillUpdate';
import {
    SkillUpdateFromJSON,
    SkillUpdateFromJSONTyped,
    SkillUpdateToJSON,
    SkillUpdateToJSONTyped,
} from './SkillUpdate';
import type { InterestUpdate } from './InterestUpdate';
import {
    InterestUpdateFromJSON,
    InterestUpdateFromJSONTyped,
    InterestUpdateToJSON,
    InterestUpdateToJSONTyped,
} from './InterestUpdate';
import type { ContactUpdate } from './ContactUpdate';
import {
    ContactUpdateFromJSON,
    ContactUpdateFromJSONTyped,
    ContactUpdateToJSON,
    ContactUpdateToJSONTyped,
} from './ContactUpdate';
import type { ExperienceUpdate } from './ExperienceUpdate';
import {
    ExperienceUpdateFromJSON,
    ExperienceUpdateFromJSONTyped,
    ExperienceUpdateToJSON,
    ExperienceUpdateToJSONTyped,
} from './ExperienceUpdate';

/**
 * 
 * @export
 * @interface ProfileUpdateRequest
 */
export interface ProfileUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof ProfileUpdateRequest
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    about?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    jobTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateRequest
     */
    linkedinUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProfileUpdateRequest
     */
    openToWork?: boolean;
    /**
     * 
     * @type {Array<ExperienceUpdate>}
     * @memberof ProfileUpdateRequest
     */
    experiences?: Array<ExperienceUpdate> | null;
    /**
     * 
     * @type {Array<EducationUpdate>}
     * @memberof ProfileUpdateRequest
     */
    educations?: Array<EducationUpdate> | null;
    /**
     * 
     * @type {Array<InterestUpdate>}
     * @memberof ProfileUpdateRequest
     */
    interests?: Array<InterestUpdate> | null;
    /**
     * 
     * @type {Array<AccomplishmentUpdate>}
     * @memberof ProfileUpdateRequest
     */
    accomplishments?: Array<AccomplishmentUpdate> | null;
    /**
     * 
     * @type {Array<ContactUpdate>}
     * @memberof ProfileUpdateRequest
     */
    contacts?: Array<ContactUpdate> | null;
    /**
     * 
     * @type {Array<SkillUpdate>}
     * @memberof ProfileUpdateRequest
     */
    skills?: Array<SkillUpdate> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfileUpdateRequest
     */
    keywords?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProfileUpdateRequest
     */
    savedJobPosts?: Array<string> | null;
}

/**
 * Check if a given object implements the ProfileUpdateRequest interface.
 */
export function instanceOfProfileUpdateRequest(value: object): value is ProfileUpdateRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function ProfileUpdateRequestFromJSON(json: any): ProfileUpdateRequest {
    return ProfileUpdateRequestFromJSONTyped(json, false);
}

export function ProfileUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'about': json['about'] == null ? undefined : json['about'],
        'location': json['location'] == null ? undefined : json['location'],
        'company': json['company'] == null ? undefined : json['company'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'openToWork': json['openToWork'] == null ? undefined : json['openToWork'],
        'experiences': json['experiences'] == null ? undefined : ((json['experiences'] as Array<any>).map(ExperienceUpdateFromJSON)),
        'educations': json['educations'] == null ? undefined : ((json['educations'] as Array<any>).map(EducationUpdateFromJSON)),
        'interests': json['interests'] == null ? undefined : ((json['interests'] as Array<any>).map(InterestUpdateFromJSON)),
        'accomplishments': json['accomplishments'] == null ? undefined : ((json['accomplishments'] as Array<any>).map(AccomplishmentUpdateFromJSON)),
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(ContactUpdateFromJSON)),
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(SkillUpdateFromJSON)),
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'savedJobPosts': json['savedJobPosts'] == null ? undefined : json['savedJobPosts'],
    };
}

export function ProfileUpdateRequestToJSON(json: any): ProfileUpdateRequest {
    return ProfileUpdateRequestToJSONTyped(json, false);
}

export function ProfileUpdateRequestToJSONTyped(value?: ProfileUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'dateOfBirth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth'] as any).toISOString()),
        'phoneNumber': value['phoneNumber'],
        'about': value['about'],
        'location': value['location'],
        'company': value['company'],
        'jobTitle': value['jobTitle'],
        'linkedinUrl': value['linkedinUrl'],
        'openToWork': value['openToWork'],
        'experiences': value['experiences'] == null ? undefined : ((value['experiences'] as Array<any>).map(ExperienceUpdateToJSON)),
        'educations': value['educations'] == null ? undefined : ((value['educations'] as Array<any>).map(EducationUpdateToJSON)),
        'interests': value['interests'] == null ? undefined : ((value['interests'] as Array<any>).map(InterestUpdateToJSON)),
        'accomplishments': value['accomplishments'] == null ? undefined : ((value['accomplishments'] as Array<any>).map(AccomplishmentUpdateToJSON)),
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(ContactUpdateToJSON)),
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(SkillUpdateToJSON)),
        'keywords': value['keywords'],
        'savedJobPosts': value['savedJobPosts'],
    };
}

