/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SkillProficiencyUpdate } from './SkillProficiencyUpdate';
import {
    SkillProficiencyUpdateFromJSON,
    SkillProficiencyUpdateFromJSONTyped,
    SkillProficiencyUpdateToJSON,
    SkillProficiencyUpdateToJSONTyped,
} from './SkillProficiencyUpdate';

/**
 * 
 * @export
 * @interface SkillUpdate
 */
export interface SkillUpdate {
    /**
     * 
     * @type {string}
     * @memberof SkillUpdate
     */
    name: string;
    /**
     * 
     * @type {SkillProficiencyUpdate}
     * @memberof SkillUpdate
     */
    proficiency: SkillProficiencyUpdate;
}



/**
 * Check if a given object implements the SkillUpdate interface.
 */
export function instanceOfSkillUpdate(value: object): value is SkillUpdate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('proficiency' in value) || value['proficiency'] === undefined) return false;
    return true;
}

export function SkillUpdateFromJSON(json: any): SkillUpdate {
    return SkillUpdateFromJSONTyped(json, false);
}

export function SkillUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'proficiency': SkillProficiencyUpdateFromJSON(json['proficiency']),
    };
}

export function SkillUpdateToJSON(json: any): SkillUpdate {
    return SkillUpdateToJSONTyped(json, false);
}

export function SkillUpdateToJSONTyped(value?: SkillUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'proficiency': SkillProficiencyUpdateToJSON(value['proficiency']),
    };
}

