/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkillDto
 */
export interface SkillDto {
    /**
     * 
     * @type {number}
     * @memberof SkillDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SkillDto
     */
    proficiency?: number;
}

/**
 * Check if a given object implements the SkillDto interface.
 */
export function instanceOfSkillDto(value: object): value is SkillDto {
    return true;
}

export function SkillDtoFromJSON(json: any): SkillDto {
    return SkillDtoFromJSONTyped(json, false);
}

export function SkillDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'proficiency': json['proficiency'] == null ? undefined : json['proficiency'],
    };
}

export function SkillDtoToJSON(json: any): SkillDto {
    return SkillDtoToJSONTyped(json, false);
}

export function SkillDtoToJSONTyped(value?: SkillDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'proficiency': value['proficiency'],
    };
}

