/* tslint:disable */
/* eslint-disable */
/**
 * FindjobnuService
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SkillProficiencyUpdate = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type SkillProficiencyUpdate = typeof SkillProficiencyUpdate[keyof typeof SkillProficiencyUpdate];


export function instanceOfSkillProficiencyUpdate(value: any): boolean {
    for (const key in SkillProficiencyUpdate) {
        if (Object.prototype.hasOwnProperty.call(SkillProficiencyUpdate, key)) {
            if (SkillProficiencyUpdate[key as keyof typeof SkillProficiencyUpdate] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SkillProficiencyUpdateFromJSON(json: any): SkillProficiencyUpdate {
    return SkillProficiencyUpdateFromJSONTyped(json, false);
}

export function SkillProficiencyUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillProficiencyUpdate {
    return json as SkillProficiencyUpdate;
}

export function SkillProficiencyUpdateToJSON(value?: SkillProficiencyUpdate | null): any {
    return value as any;
}

export function SkillProficiencyUpdateToJSONTyped(value: any, ignoreDiscriminator: boolean): SkillProficiencyUpdate {
    return value as SkillProficiencyUpdate;
}

