/* tslint:disable */
/* eslint-disable */
/**
 * findjobnuAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Interest } from './Interest';
import {
    InterestFromJSON,
    InterestFromJSONTyped,
    InterestToJSON,
    InterestToJSONTyped,
} from './Interest';
import type { Experience } from './Experience';
import {
    ExperienceFromJSON,
    ExperienceFromJSONTyped,
    ExperienceToJSON,
    ExperienceToJSONTyped,
} from './Experience';
import type { Skill } from './Skill';
import {
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
    SkillToJSONTyped,
} from './Skill';
import type { Accomplishment } from './Accomplishment';
import {
    AccomplishmentFromJSON,
    AccomplishmentFromJSONTyped,
    AccomplishmentToJSON,
    AccomplishmentToJSONTyped,
} from './Accomplishment';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
    UserProfileToJSONTyped,
} from './UserProfile';
import type { Education } from './Education';
import {
    EducationFromJSON,
    EducationFromJSONTyped,
    EducationToJSON,
    EducationToJSONTyped,
} from './Education';
import type { BasicInfo } from './BasicInfo';
import {
    BasicInfoFromJSON,
    BasicInfoFromJSONTyped,
    BasicInfoToJSON,
    BasicInfoToJSONTyped,
} from './BasicInfo';
import type { Contact } from './Contact';
import {
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
    ContactToJSONTyped,
} from './Contact';

/**
 * 
 * @export
 * @interface WorkProfile
 */
export interface WorkProfile {
    /**
     * 
     * @type {number}
     * @memberof WorkProfile
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkProfile
     */
    userProfileId: number;
    /**
     * 
     * @type {UserProfile}
     * @memberof WorkProfile
     */
    userProfile: UserProfile;
    /**
     * 
     * @type {BasicInfo}
     * @memberof WorkProfile
     */
    basicInfo?: BasicInfo;
    /**
     * 
     * @type {Array<Experience>}
     * @memberof WorkProfile
     */
    experiences?: Array<Experience> | null;
    /**
     * 
     * @type {Array<Education>}
     * @memberof WorkProfile
     */
    educations?: Array<Education> | null;
    /**
     * 
     * @type {Array<Interest>}
     * @memberof WorkProfile
     */
    interests?: Array<Interest> | null;
    /**
     * 
     * @type {Array<Accomplishment>}
     * @memberof WorkProfile
     */
    accomplishments?: Array<Accomplishment> | null;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof WorkProfile
     */
    contacts?: Array<Contact> | null;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof WorkProfile
     */
    skills?: Array<Skill> | null;
}

/**
 * Check if a given object implements the WorkProfile interface.
 */
export function instanceOfWorkProfile(value: object): value is WorkProfile {
    if (!('userProfileId' in value) || value['userProfileId'] === undefined) return false;
    if (!('userProfile' in value) || value['userProfile'] === undefined) return false;
    return true;
}

export function WorkProfileFromJSON(json: any): WorkProfile {
    return WorkProfileFromJSONTyped(json, false);
}

export function WorkProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userProfileId': json['userProfileId'],
        'userProfile': UserProfileFromJSON(json['userProfile']),
        'basicInfo': json['basicInfo'] == null ? undefined : BasicInfoFromJSON(json['basicInfo']),
        'experiences': json['experiences'] == null ? undefined : ((json['experiences'] as Array<any>).map(ExperienceFromJSON)),
        'educations': json['educations'] == null ? undefined : ((json['educations'] as Array<any>).map(EducationFromJSON)),
        'interests': json['interests'] == null ? undefined : ((json['interests'] as Array<any>).map(InterestFromJSON)),
        'accomplishments': json['accomplishments'] == null ? undefined : ((json['accomplishments'] as Array<any>).map(AccomplishmentFromJSON)),
        'contacts': json['contacts'] == null ? undefined : ((json['contacts'] as Array<any>).map(ContactFromJSON)),
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(SkillFromJSON)),
    };
}

export function WorkProfileToJSON(json: any): WorkProfile {
    return WorkProfileToJSONTyped(json, false);
}

export function WorkProfileToJSONTyped(value?: WorkProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userProfileId': value['userProfileId'],
        'userProfile': UserProfileToJSON(value['userProfile']),
        'basicInfo': BasicInfoToJSON(value['basicInfo']),
        'experiences': value['experiences'] == null ? undefined : ((value['experiences'] as Array<any>).map(ExperienceToJSON)),
        'educations': value['educations'] == null ? undefined : ((value['educations'] as Array<any>).map(EducationToJSON)),
        'interests': value['interests'] == null ? undefined : ((value['interests'] as Array<any>).map(InterestToJSON)),
        'accomplishments': value['accomplishments'] == null ? undefined : ((value['accomplishments'] as Array<any>).map(AccomplishmentToJSON)),
        'contacts': value['contacts'] == null ? undefined : ((value['contacts'] as Array<any>).map(ContactToJSON)),
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(SkillToJSON)),
    };
}

